require('dotenv').config();
const {Client,GatewayIntentBits,EmbedBuilder}=require('discord.js');
const Database=require('better-sqlite3');
const {slashCommands,prefixCommands,commandListEmbed}=require('./commands');
const token=process.env.DISCORD_TOKEN;if(!token)throw new Error('DISCORD_TOKEN missing');
const prefix=process.env.PREFIX||'.';
const db=new Database('bot.sqlite');db.exec('CREATE TABLE IF NOT EXISTS warns(guild TEXT,user TEXT,reason TEXT,by TEXT,at INTEGER); CREATE TABLE IF NOT EXISTS money(user TEXT PRIMARY KEY,balance INTEGER DEFAULT 0,daily INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS xp(guild TEXT,user TEXT,xp INTEGER DEFAULT 0,level INTEGER DEFAULT 0,PRIMARY KEY(guild,user));');
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const e=(t,d)=>new EmbedBuilder().setTitle(t).setDescription(d).setColor(0x5865f2).setTimestamp();const opt=(i,n)=>i.options.getUser(n)||i.user;const money=u=>{let r=db.prepare('SELECT * FROM money WHERE user=?').get(u);if(!r){db.prepare('INSERT INTO money(user,balance,daily) VALUES(?,?,?)').run(u,0,0);r=db.prepare('SELECT * FROM money WHERE user=?').get(u)}return r};
async function run(i,n){
 if(n==='help')return i.reply({embeds:[commandListEmbed()]});if(n==='ping')return i.reply(`🏓 ${client.ws.ping}ms`);if(n==='botinfo')return i.reply({embeds:[e('Bot Info',`Servers: ${client.guilds.cache.size}\nSlash: ${slashCommands.length}\nPrefix: ${prefixCommands.length}\nPrefix: ${prefix}`)]});if(n==='serverinfo')return i.reply({embeds:[e(i.guild.name,`Members: ${i.guild.memberCount}\nChannels: ${i.guild.channels.cache.size}\nRoles: ${i.guild.roles.cache.size}`)]});
 if(['userinfo','member'].includes(n)){let u=opt(i,'user');return i.reply({embeds:[e(u.tag,`ID: ${u.id}\nCreated: <t:${Math.floor(u.createdTimestamp/1000)}:R>`).setThumbnail(u.displayAvatarURL())]})}if(n==='avatar'){let u=opt(i,'user');return i.reply(u.displayAvatarURL({size:1024}))}if(n==='membercount')return i.reply(`👥 ${i.guild.memberCount}`);
 if(['kick','ban','timeout','untimeout','warn'].includes(n)){let m=i.options.getMember('user');if(!m)return i.reply({content:'Member not found.',ephemeral:true});let r=i.options.getString('reason')||'No reason';try{if(n==='kick')await m.kick(r);if(n==='ban')await m.ban({reason:r});if(n==='timeout')await m.timeout(i.options.getInteger('duration')||600000,r);if(n==='untimeout')await m.timeout(null,r);if(n==='warn')db.prepare('INSERT INTO warns VALUES(?,?,?,?,?)').run(i.guildId,m.id,r,i.user.id,Date.now());return i.reply({embeds:[e('Moderation',`${n} → ${m.user.tag}\n${r}`)]})}catch(x){return i.reply({content:x.message,ephemeral:true})}}
 if(['clear','purge'].includes(n)){let a=Math.min(i.options.getInteger('amount')||10,100);await i.channel.bulkDelete(a,true);return i.reply({content:`🧹 Deleted ${a}`,ephemeral:true})}if(['lock','unlock'].includes(n)){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:n==='unlock'});return i.reply(`Channel ${n}ed.`)}if(n==='slowmode'){let s=Math.min(i.options.getInteger('seconds')||5,21600);await i.channel.setRateLimitPerUser(s);return i.reply(`Slowmode ${s}s`)}
 if(['balance','economy'].includes(n)){return i.reply({embeds:[e('💰 Wallet',`Balance: ${money(i.user.id).balance} coins`)]})}if(n==='daily'){let r=money(i.user.id),now=Date.now();if(now-r.daily<86400000)return i.reply({content:'Daily already claimed.',ephemeral:true});db.prepare('UPDATE money SET balance=balance+500,daily=? WHERE user=?').run(now,i.user.id);return i.reply('🎁 +500 coins')}if(n==='work'){let a=100+Math.floor(Math.random()*401);money(i.user.id);db.prepare('UPDATE money SET balance=balance+? WHERE user=?').run(a,i.user.id);return i.reply(`💼 +${a} coins`)}if(n==='coinflip'||n==='dice')return i.reply(n==='coinflip'?`🪙 ${Math.random()<.5?'Heads':'Tails'}`:`🎲 ${1+Math.floor(Math.random()*6)}`);if(n==='8ball')return i.reply(['Yes.','No.','Maybe.','Definitely.','Ask later.'][Math.floor(Math.random()*5)]);
 if(n==='roll'){let m=i.options.getInteger('max')||100;return i.reply(`🎲 ${1+Math.floor(Math.random()*m)}`)}if(n==='choose'){let a=(i.options.getString('options')||'').split('|').filter(Boolean);return i.reply(a.length?`🎯 ${a[Math.floor(Math.random()*a.length)]}`:'Use | between choices')}if(n==='calculator'){let x=i.options.getString('expression');if(!x||!/^[0-9+\-*/().% ]+$/.test(x))return i.reply('Basic arithmetic only.');try{return i.reply(String(Function(`return (${x})`)()))}catch{return i.reply('Invalid expression')}}if(n==='config')return i.reply({embeds:[e('⚙️ Configuration','Use environment variables for global settings. Per-server modules are being added to the same command registry.')]});
 return i.reply({embeds:[e(`/${n}`,'Registered in the Aarav All-In-One v3 framework. This command is ready for its feature module.')],ephemeral:true});}
client.once('ready',async()=>{let data=slashCommands.map(x=>({name:x.name,description:x.description}));if(process.env.DEV_GUILD_ID){let g=await client.guilds.fetch(process.env.DEV_GUILD_ID);await g.commands.set(data)}else await client.application.commands.set(data);console.log(`✅ ${client.user.tag} online | ${slashCommands.length} slash | ${prefixCommands.length} prefix`)});
client.on('interactionCreate',i=>i.isChatInputCommand()?run(i,i.commandName).catch(console.error):null);
client.on('messageCreate',m=>{if(m.author.bot||!m.guild||!m.content.startsWith(prefix))return;let [n,...a]=m.content.slice(prefix.length).trim().split(/\s+/);n=n?.toLowerCase();if(!prefixCommands.includes(n))return;if(['help','h','commands'].includes(n))return m.reply({embeds:[commandListEmbed()]});let fake={guildId:m.guild.id,guild:m.guild,user:m.author,member:m.member,channel:m.channel,options:{getUser:()=>m.mentions.users.first(),getMember:()=>m.mentions.members.first()||m.member,getString:()=>a.join(' '),getInteger:()=>Number(a[0])||undefined},reply:x=>m.reply(typeof x==='string'?x:(x.content||x))};run(fake,n).catch(x=>m.reply(`Error: ${x.message}`))});client.login(token);
