require('dotenv').config();
const http=require('http');
const fs=require('fs');
const path=require('path');
const {Client,GatewayIntentBits,EmbedBuilder,PermissionFlagsBits,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
const Database=require('better-sqlite3');
const {slashCommands,prefixCommands,commandListEmbed,serversEmbed}=require('./commands');
const statistics=require('./modules/statistics');
const invites=require('./modules/invites');
const token=process.env.DISCORD_TOKEN;if(!token)throw new Error('DISCORD_TOKEN missing');
const prefix=process.env.PREFIX||'.';const startedAt=Date.now();
const dbFile=process.env.DB_FILE||'bot.sqlite';
const dbDir=path.dirname(path.resolve(dbFile));
if(dbDir && dbDir!=='.') fs.mkdirSync(dbDir,{recursive:true});
const db=new Database(dbFile);
const port=Number(process.env.PORT)||10000;
const health=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({status:'ok',bot:client?.user?.tag||'starting',uptime:Math.floor((Date.now()-startedAt)/1000)}));});
health.listen(port,'0.0.0.0',()=>console.log(`🌐 Web server listening on 0.0.0.0:${port}`));
statistics.ensure(db);invites.ensure(db);db.exec('CREATE TABLE IF NOT EXISTS warns(guild TEXT,user TEXT,reason TEXT,by TEXT,at INTEGER); CREATE TABLE IF NOT EXISTS money(user TEXT PRIMARY KEY,balance INTEGER DEFAULT 0,daily INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS xp(guild TEXT,user TEXT,xp INTEGER DEFAULT 0,level INTEGER DEFAULT 0,PRIMARY KEY(guild,user));');
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.GuildPresences]});
const e=(t,d)=>new EmbedBuilder().setTitle(t).setDescription(d).setColor(0x5865f2).setTimestamp();const opt=(i,n)=>i.options.getUser?.(n)||i.user;const money=u=>{let r=db.prepare('SELECT * FROM money WHERE user=?').get(u);if(!r){db.prepare('INSERT INTO money(user,balance,daily) VALUES(?,?,?)').run(u,0,0);r=db.prepare('SELECT * FROM money WHERE user=?').get(u)}return r};
const adminOnly=new Set(['kick','ban','unban','timeout','untimeout','warn','clear','purge','lock','unlock','slowmode','automod','antilink','antispam','antiraid','antialt','welcome','goodbye','autorole','setprefix','setmodlog','setwelcome','setgoodbye','setlog','setverification','counters','counter','statsreset','setxp','addxp','removexp','ticket','close','claim','giveaway','gstart','gend','greroll','reactionrole','autorolemenu','config','announce','nuke','lockdown','unlockdown']);
function permitted(i,n){if(!adminOnly.has(n))return true;return i.member?.permissions?.has(PermissionFlagsBits.ManageGuild)||i.member?.permissions?.has(PermissionFlagsBits.ManageMessages)||i.member?.permissions?.has(PermissionFlagsBits.Administrator)}
function inviteUrl(guildId){const clientId=process.env.CLIENT_ID||client.user.id;return `https://discord.com/oauth2/authorize?client_id=${clientId}&scope=bot%20applications.commands&permissions=8${guildId?`&guild_id=${guildId}&disable_guild_select=true`:''}`}
async function run(i,n){
 if(!permitted(i,n))return i.reply({content:'⛔ You need the appropriate server management permission to use this command.',ephemeral:true});
 if(n==='help')return i.reply({embeds:[commandListEmbed()]});
 if(n==='uptime'){const s=Math.floor((Date.now()-startedAt)/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;return i.reply({embeds:[e('⏱️ Bot Uptime',`**${d}d ${h}h ${m}m ${sec}s**\nStarted <t:${Math.floor(startedAt/1000)}:R>`)]});}
 if(n==='invite'||n==='invitebot')return i.reply({embeds:[e('🤖 Invite Aarav All-In-One','Use the button below to add the bot to a server.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setLabel('Invite Bot').setStyle(ButtonStyle.Link).setURL(inviteUrl()))]});
 if(n==='servers')return i.reply(serversEmbed(client));
 if(n==='stats'||n==='serverstats'||n==='memberstats'||n==='mystats'||n==='userstats'||n==='me'||n==='statleaderboard'||n==='statlb'||n==='topstats'||n==='counters'||n==='counter'||n==='statcounter'||n==='statcounters'||n==='statsreset')return statistics.command(i,n,db);
 if(['invites','invitetop','inviteleaderboard'].includes(n))return invites.command(i,n,db);
 if(n==='ping')return i.reply(`🏓 ${client.ws.ping}ms`);if(n==='botinfo')return i.reply({embeds:[e('Bot Info',`Servers: ${client.guilds.cache.size}\nSlash: ${slashCommands.length}\nClient: ${prefixCommands.length}\nPrefix: ${prefix}`)]});if(n==='serverinfo')return i.reply({embeds:[e(i.guild.name,`Members: ${i.guild.memberCount}\nChannels: ${i.guild.channels.cache.size}\nRoles: ${i.guild.roles.cache.size}`)]});
 if(['userinfo','member'].includes(n)){let u=opt(i,'user');return i.reply({embeds:[e(u.tag,`ID: ${u.id}\nCreated: <t:${Math.floor(u.createdTimestamp/1000)}:R>`).setThumbnail(u.displayAvatarURL())]})}if(n==='avatar'){let u=opt(i,'user');return i.reply(u.displayAvatarURL({size:1024}))}if(n==='membercount')return i.reply(`👥 ${i.guild.memberCount}`);
 if(n==='announce'){const channel=i.options.getChannel?.('channel')||i.channel;const message=i.options.getString?.('message')||'';const ping=i.options.getString?.('ping')||'none';const role=i.options.getRole?.('role');const target=ping==='everyone'?'@everyone':ping==='here'?'@here':ping==='role'&&role?`<@&${role.id}>`:'';await channel.send({content:target,embeds:[e(i.options.getString?.('title')||'📢 Announcement',message)],allowedMentions:{parse:target==='@everyone'||target==='@here'?[ping]:[],roles:role&&ping==='role'?[role.id]:[]}});return i.reply({content:`✅ Announcement sent to ${channel}.`,ephemeral:true});}
 if(['kick','ban','timeout','untimeout','warn'].includes(n)){let m=i.options.getMember?.('user');if(!m)return i.reply({content:'Member not found.',ephemeral:true});let r=i.options.getString?.('reason')||'No reason';try{if(n==='kick')await m.kick(r);if(n==='ban')await m.ban({reason:r});if(n==='timeout')await m.timeout(i.options.getInteger?.('duration')||600000,r);if(n==='untimeout')await m.timeout(null,r);if(n==='warn')db.prepare('INSERT INTO warns VALUES(?,?,?,?,?)').run(i.guildId,m.id,r,i.user.id,Date.now());return i.reply({embeds:[e('Moderation',`${n} → ${m.user.tag}\n${r}`)]})}catch(x){return i.reply({content:x.message,ephemeral:true})}}
 if(['clear','purge'].includes(n)){let a=Math.min(i.options.getInteger?.('amount')||10,100);await i.channel.bulkDelete(a,true);return i.reply({content:`🧹 Deleted ${a}`,ephemeral:true})}if(['lock','unlock'].includes(n)){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:n==='unlock'});return i.reply(`Channel ${n==='lock'?'unlocked':'locked'}.`)}if(n==='slowmode'){let s=Math.min(i.options.getInteger?.('seconds')||5,21600);await i.channel.setRateLimitPerUser(s);return i.reply(`Slowmode ${s}s`)}
 if(['balance','economy'].includes(n))return i.reply({embeds:[e('💰 Wallet',`Balance: ${money(i.user.id).balance} coins`)]});if(n==='daily'){let r=money(i.user.id),now=Date.now();if(now-r.daily<86400000)return i.reply({content:'Daily already claimed.',ephemeral:true});db.prepare('UPDATE money SET balance=balance+500,daily=? WHERE user=?').run(now,i.user.id);return i.reply('🎁 +500 coins')}if(n==='work'){let a=100+Math.floor(Math.random()*401);money(i.user.id);db.prepare('UPDATE money SET balance=balance+? WHERE user=?').run(a,i.user.id);return i.reply(`💼 +${a} coins`)}if(n==='coinflip'||n==='dice')return i.reply(n==='coinflip'?`🪙 ${Math.random()<.5?'Heads':'Tails'}`:`🎲 ${1+Math.floor(Math.random()*6)}`);if(n==='8ball')return i.reply(['Yes.','No.','Maybe.','Definitely.','Ask later.'][Math.floor(Math.random()*5)]);if(n==='roll'){let m=i.options.getInteger?.('max')||100;return i.reply(`🎲 ${1+Math.floor(Math.random()*m)}`)}if(n==='choose'){let a=(i.options.getString?.('options')||'').split('|').filter(Boolean);return i.reply(a.length?`🎯 ${a[Math.floor(Math.random()*a.length)]}`:'Use | between choices')}if(n==='calculator'){let x=i.options.getString?.('expression');if(!x||!/^[0-9+\-*/().% ]+$/.test(x))return i.reply('Basic arithmetic only.');try{return i.reply(String(Function(`return (${x})`)()))}catch{return i.reply('Invalid expression')}}
 return i.reply({embeds:[e(`/${n}`,'This command is registered in the modular all-in-one framework.')],ephemeral:true});}
client.once('ready',async()=>{try{for(const g of client.guilds.cache.values())await invites.cacheGuild(g,db);if(process.env.DEV_GUILD_ID){const g=await client.guilds.fetch(process.env.DEV_GUILD_ID);await g.commands.set([]);await g.commands.set(slashCommands)}else{await client.application.commands.set([]);await client.application.commands.set(slashCommands)}}catch(err){console.error('Command sync failed:',err)}for(const g of client.guilds.cache.values())statistics.updateCounters(g,db).catch(()=>{});console.log(`✅ ${client.user.tag} online | commands wiped + rebuilt | ${slashCommands.length} slash | ${prefixCommands.length} client`)});
client.on('interactionCreate',async i=>{try{if(i.isChatInputCommand())return run(i,i.commandName);if(i.isStringSelectMenu()&&i.customId==='servers:select'){const guild=client.guilds.cache.get(i.values[0]);if(!guild)return i.reply({content:'Server not found.',ephemeral:true});return i.update({embeds:[e(`🌐 ${guild.name}`,`Members: **${guild.memberCount||'?'}**\nThis bot is currently installed here.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setLabel('Invite Bot to This Server').setStyle(ButtonStyle.Link).setURL(inviteUrl(guild.id)))]});}}catch(err){console.error(err);if(!i.replied&&!i.deferred)i.reply({content:`Error: ${err.message}`,ephemeral:true}).catch(()=>{})}});
client.on('messageCreate',async m=>{if(m.author.bot||!m.guild)return;statistics.recordMessage(db,m.guild.id,m.author.id,m.channel.id);if(!m.content.startsWith(prefix))return;let [n,...a]=m.content.slice(prefix.length).trim().split(/\s+/);n=n?.toLowerCase();if(!prefixCommands.includes(n))return;if(['help','h','commands'].includes(n))return m.reply({embeds:[commandListEmbed()]});if(n==='servers'||n==='serverlist')return m.reply(serversEmbed(client));if(n==='uptime'||n==='up')return m.reply(`⏱️ Uptime: ${Math.floor((Date.now()-startedAt)/1000)} seconds`);let fake={guildId:m.guild.id,guild:m.guild,user:m.author,member:m.member,channel:m.channel,channelId:m.channel.id,options:{getUser:()=>m.mentions.users.first(),getMember:()=>m.mentions.members.first()||m.member,getRole:()=>m.mentions.roles.first(),getChannel:()=>m.mentions.channels.first()||m.channel,getString:()=>a.join(' '),getInteger:()=>Number(a[0])||undefined,getBoolean:()=>['on','true','enable','enabled'].includes(String(a[0]).toLowerCase())},reply:x=>m.reply(typeof x==='string'?x:(x.content||x))};run(fake,n).catch(x=>m.reply(`Error: ${x.message}`))});
const voiceStarted=new Map();client.on('voiceStateUpdate',(oldState,newState)=>{const key=`${newState.guild.id}:${newState.id}`;if(!oldState.channelId&&newState.channelId)voiceStarted.set(key,{at:Date.now(),channel:newState.channelId});if(oldState.channelId&&!newState.channelId){const s=voiceStarted.get(key);if(s){statistics.addVoice(db,newState.guild.id,newState.id,s.channel,Math.max(0,Math.floor((Date.now()-s.at)/1000)));voiceStarted.delete(key)}}});
client.on('guildMemberAdd',async m=>{statistics.member(db,m.guild.id,m.id);statistics.updateCounters(m.guild,db).catch(()=>{});const hit=await invites.onJoin(m,db).catch(()=>null);if(hit){const ch=m.guild.systemChannel;if(ch)ch.send(`📨 ${m.user} joined using an invite from <@${hit.inviter}>${hit.fake?' (possible fake invite)':''}.`).catch(()=>{})}});client.on('guildMemberRemove',m=>{invites.onLeave(m,db);statistics.updateCounters(m.guild,db).catch(()=>{})});
setInterval(()=>{for(const g of client.guilds.cache.values())statistics.updateCounters(g,db).catch(()=>{})},5*60*1000);client.login(token);