require('dotenv').config();
const {Client,GatewayIntentBits,PermissionsBitField,EmbedBuilder,REST,Routes}=require('discord.js');
const Database=require('better-sqlite3');
const http=require('http');
const tickets=require('./modules/tickets');
const applications=require('./modules/applications');
const logging=require('./modules/logging');
const embeds=require('./modules/embeds');
const PREFIX=process.env.PREFIX||'.';
if(!process.env.DISCORD_TOKEN)throw new Error('DISCORD_TOKEN is required');
const db=new Database(process.env.DB_FILE||'data.sqlite');
tickets.init(db);applications.init(db);logging.init(db);
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildModeration,GatewayIntentBits.GuildVoiceStates]});
function e(title,description){return new EmbedBuilder().setTitle(title).setDescription(description).setColor(0x5865f2).setTimestamp()}
const categories={moderation:['ban','kick','timeout','warn','purge','lock','unlock','slowmode'],security:['automod','antilink','antispam','antiraid','verification'],community:['welcome','goodbye','autorole','reactionrole','level','rank','leaderboard'],support:['ticket','ticketpanel','application','applicationpanel','transcript','logs'],utility:['help','announce','embed','userinfo','serverinfo','avatar','remind','poll','tts'],music:['play','pause','resume','skip','stop','queue','nowplaying','volume','loop'],fun:['8ball','dice','choose','roll'],economy:['balance','daily','work','pay','shop','inventory'],admin:['config','setprefix','setlog','settranscripts','setcategory']};
const slash=[];for(const [category,names] of Object.entries(categories))for(const name of names)slash.push({name,description:`${category} command: ${name}`.slice(0,100)});
async function help(i){const list=Object.entries(categories).map(([k,v])=>`### ${k[0].toUpperCase()+k.slice(1)}\n${v.map(x=>`\`/${x}\``).join(' • ')}`).join('\n');return i.reply({embeds:[e('🤖 Aarav All-In-One',`Interactive command center\n\n${list}`)],ephemeral:false})}
async function announce(i){if(!i.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return i.reply({content:'Manage Messages permission required.',ephemeral:true});const channel=i.options.getChannel('channel');const text=i.options.getString('message');const ping=i.options.getString('ping')||'none';const allowed=ping==='everyone'?{parse:['everyone']} : ping==='here'?{parse:['everyone']} : ping==='role'&&i.options.getRole('role')?{roles:[i.options.getRole('role').id]}:{users:[]};await channel.send({content:ping==='everyone'?'@everyone':ping==='here'?'@here':ping==='role'?`<@&${i.options.getRole('role').id}>`:'',embeds:[e('📢 Announcement',text)],allowedMentions:allowed});return i.reply({content:`Announcement sent to ${channel}.`,ephemeral:true})}
async function run(i){if(!i.isChatInputCommand())return;if(i.commandName==='help')return help(i);if(i.commandName==='announce')return announce(i);if(i.commandName==='ticketpanel')return i.reply({...tickets.panel(db,i.guildId)});if(i.commandName==='applicationpanel')return i.reply({...applications.panel(db,i.guildId)});if(i.commandName==='embed')return i.showModal(embeds.editor());if(i.commandName==='transcript')return i.reply({content:'Transcripts are generated automatically when tickets close and delivered to the configured transcript/log channel.',ephemeral:true});if(i.commandName==='logs')return i.reply({content:'Use the server configuration module to assign event-specific log channels.',ephemeral:true});if(i.commandName==='tts'){const text=i.options.getString('text');if(!text)return i.reply({content:'Provide text.',ephemeral:true});return i.reply({content:`🔊 TTS requested: ${text}`,tts:true})}return i.reply({embeds:[e(`/${i.commandName}`,'This command is registered in the modular v4 architecture. Its feature module can be configured from Discord.')],ephemeral:true})}
client.on('interactionCreate',async i=>{try{if(i.isChatInputCommand())return run(i);if(await tickets.handle(i,{db,client}))return;if(await applications.handle(i,{db,client}))return;if(await embeds.handle(i,{db,client}))return}catch(err){console.error(err);if(!i.replied&&!i.deferred)await i.reply({content:'An internal error occurred.',ephemeral:true}).catch(()=>{})}});
client.once('ready',async()=>{const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);const data=slash.map(x=>({name:x.name,description:x.description,options:x.name==='announce'?[{type:7,name:'channel',description:'Destination channel',required:true},{type:3,name:'message',description:'Announcement text',required:true},{type:3,name:'ping',description:'none, everyone, here or role',required:false,choices:[{name:'None',value:'none'},{name:'Everyone',value:'everyone'},{name:'Here',value:'here'},{name:'Role',value:'role'}]},{type:8,name:'role',description:'Role to mention',required:false}]:x.name==='tts'?[{type:3,name:'text',description:'Text to speak',required:true}]:[] }));if(process.env.DEV_GUILD_ID)await rest.put(Routes.applicationGuildCommands(client.user.id,process.env.DEV_GUILD_ID),{body:data});else await rest.put(Routes.applicationCommands(client.user.id),{body:data});logging.bind(client,db);console.log(`Ready as ${client.user.tag} | ${slash.length} slash commands`)});
client.on('messageCreate',async m=>{if(m.author.bot||!m.guild||!m.content.startsWith(PREFIX))return;const [cmd,...args]=m.content.slice(PREFIX.length).trim().split(/\s+/);if(cmd?.toLowerCase()==='help')return m.reply({embeds:[e('🤖 Client Commands',`Prefix: \`${PREFIX}\`\nUse \`${PREFIX}help\` to browse commands.`)]});if(cmd?.toLowerCase()==='announce'&&m.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return m.reply('Use /announce for the interactive announcement builder.');});
http.createServer((req,res)=>{res.writeHead(req.url==='/health'?200:404,{'content-type':'application/json'});res.end(JSON.stringify({ok:req.url==='/health',bot:client.isReady()}))}).listen(Number(process.env.PORT||10000),'0.0.0.0');
client.login(process.env.DISCORD_TOKEN);
