const {ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,EmbedBuilder,PermissionFlagsBits}=require('discord.js');
function init(db){db.exec(`CREATE TABLE IF NOT EXISTS application_forms(guild TEXT NOT NULL,id TEXT NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',questions TEXT DEFAULT '[]',review_channel TEXT,accept_role TEXT,deny_message TEXT DEFAULT '',PRIMARY KEY(guild,id));CREATE TABLE IF NOT EXISTS applications(id INTEGER PRIMARY KEY AUTOINCREMENT,guild TEXT,form_id TEXT,user TEXT,answers TEXT,status TEXT DEFAULT 'pending',reviewer TEXT,created INTEGER);CREATE TABLE IF NOT EXISTS application_panels(guild TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT DEFAULT '',color TEXT DEFAULT '5865f2',footer TEXT DEFAULT '',style TEXT DEFAULT 'dropdown');`);}
function ensureDefault(db,guild){let form=db.prepare('SELECT * FROM application_forms WHERE guild=? ORDER BY id LIMIT 1').get(guild);if(!form){db.prepare('INSERT INTO application_forms(guild,id,title,description,questions) VALUES(?,?,?,?,?)').run(guild,'general','General Application','Complete the application below.',JSON.stringify(['Why do you want to join?','Tell us about yourself.','What can you contribute?']));form=db.prepare('SELECT * FROM application_forms WHERE guild=? AND id=?').get(guild,'general');}return form;}
function ensurePanel(db,guild,defaults={}){let p=db.prepare('SELECT * FROM application_panels WHERE guild=?').get(guild);if(!p){db.prepare('INSERT INTO application_panels(guild,title,description,color,footer,style) VALUES(?,?,?,?,?,?)').run(guild,defaults.title||'📝 Applications',defaults.description||'Choose an application below.',normalColor(defaults.color||'5865f2'),'','dropdown');p=db.prepare('SELECT * FROM application_panels WHERE guild=?').get(guild);}return p;}
function normalColor(v){const s=String(v||'5865f2').replace('#','').trim();return /^[0-9a-f]{6}$/i.test(s)?s.toUpperCase():'5865F2';}
function color(v){return parseInt(normalColor(v),16);}
function readQuestions(form){try{const parsed=JSON.parse(form.questions||'[]');return Array.isArray(parsed)?parsed.slice(0,5):[];}catch{return[];}}
function questionText(question){return typeof question==='string'?question:String(question?.label||'Question');}
function panel(db,guild,overrides={}){const p0=ensurePanel(db,guild,overrides),p={...p0,...overrides,color:normalColor(overrides.color||p0.color)},forms=db.prepare('SELECT * FROM application_forms WHERE guild=? ORDER BY title').all(guild),list=forms.length?forms:[ensureDefault(db,guild)];const embed=new EmbedBuilder().setTitle(p.title||'📝 Applications').setDescription(p.description||'Choose an application below.').setColor(color(p.color));if(p.footer)embed.setFooter({text:String(p.footer).slice(0,2048)});const components=[];if(String(p.style).toLowerCase()==='buttons'&&list.length<=20){for(let n=0;n<list.length;n+=5){components.push(new ActionRowBuilder().addComponents(...list.slice(n,n+5).map(form=>new ButtonBuilder().setCustomId(`application:select:${form.id}`).setLabel(String(form.title||'Apply').slice(0,80)).setStyle(ButtonStyle.Primary))));}}else components.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('application:select').setPlaceholder('Choose an application').addOptions(list.slice(0,25).map(form=>({label:String(form.title||'Application').slice(0,100),value:String(form.id),description:String(form.description||'Apply now').slice(0,100)})))));if(components.length<5)components.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('application:editpanel').setLabel('Edit Panel').setEmoji('⚙️').setStyle(ButtonStyle.Secondary)));return {embeds:[embed],components};}
function editModal(db,guild){const p=ensurePanel(db,guild);return new ModalBuilder().setCustomId('application:editpanel:submit').setTitle('Edit Application Panel').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('title').setLabel('Panel title').setStyle(TextInputStyle.Short).setValue(String(p.title||'').slice(0,256)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Panel description').setStyle(TextInputStyle.Paragraph).setValue(String(p.description||'').slice(0,4000)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('color').setLabel('Embed color (HEX)').setStyle(TextInputStyle.Short).setValue(normalColor(p.color)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('footer').setLabel('Footer (optional)').setStyle(TextInputStyle.Short).setValue(String(p.footer||'').slice(0,2048)).setRequired(false)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('style').setLabel('Layout: dropdown or buttons').setStyle(TextInputStyle.Short).setValue(String(p.style||'dropdown')).setRequired(true)));}
function canManage(i){return !!(i.member?.permissions?.has(PermissionFlagsBits.Administrator)||i.member?.permissions?.has(PermissionFlagsBits.ManageGuild));}
async function start(interaction,db,form){const questions=readQuestions(form);if(!questions.length)return interaction.reply({content:'❌ This application has no questions configured.',ephemeral:true});const modal=new ModalBuilder().setCustomId(`application:submit:${form.id}`).setTitle(String(form.title||'Application').slice(0,45));for(let index=0;index<questions.length;index++){const question=questions[index],label=questionText(question).slice(0,45)||`Question ${index+1}`,style=question&&typeof question==='object'&&question.style==='short'?TextInputStyle.Short:TextInputStyle.Paragraph,required=!(question&&typeof question==='object'&&question.required===false);modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(`q${index}`).setLabel(label).setStyle(style).setRequired(required).setMaxLength(1000)));}return interaction.showModal(modal);}
async function submit(interaction,db,form){const questions=readQuestions(form),answers=questions.map((question,index)=>({question:questionText(question),answer:interaction.fields.getTextInputValue(`q${index}`)}));const result=db.prepare('INSERT INTO applications(guild,form_id,user,answers,created) VALUES(?,?,?,?,?)').run(interaction.guildId,form.id,interaction.user.id,JSON.stringify(answers),Date.now());const reviewChannel=form.review_channel?interaction.guild.channels.cache.get(form.review_channel):null;if(reviewChannel&&reviewChannel.isTextBased()){const embed=new EmbedBuilder().setTitle(`📝 Application #${result.lastInsertRowid}`).setDescription(`Applicant: ${interaction.user}\nForm: **${form.title}**\n\n`+answers.map(x=>`**${x.question}**\n${x.answer}`).join('\n\n')).setColor(0x5865f2).setTimestamp();await reviewChannel.send({embeds:[embed],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`application:accept:${result.lastInsertRowid}`).setLabel('Accept').setEmoji('✅').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`application:deny:${result.lastInsertRowid}`).setLabel('Deny').setEmoji('❌').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`application:hold:${result.lastInsertRowid}`).setLabel('Hold').setEmoji('⏸️').setStyle(ButtonStyle.Secondary))]});}return interaction.reply({content:'✅ Application submitted successfully.',ephemeral:true});}
async function handle(interaction,ctx){const {db}=ctx;
  if(interaction.isButton()&&interaction.customId==='application:editpanel'){if(!canManage(interaction))return interaction.reply({content:'⛔ Only server managers can edit application panels.',ephemeral:true});return interaction.showModal(editModal(db,interaction.guildId));}
  if(interaction.isModalSubmit()&&interaction.customId==='application:editpanel:submit'){if(!canManage(interaction))return interaction.reply({content:'⛔ Only server managers can edit application panels.',ephemeral:true});const title=interaction.fields.getTextInputValue('title'),description=interaction.fields.getTextInputValue('description'),c=normalColor(interaction.fields.getTextInputValue('color')),footer=interaction.fields.getTextInputValue('footer'),style=['buttons','dropdown'].includes(interaction.fields.getTextInputValue('style').toLowerCase())?interaction.fields.getTextInputValue('style').toLowerCase():'dropdown';db.prepare('INSERT INTO application_panels(guild,title,description,color,footer,style) VALUES(?,?,?,?,?,?) ON CONFLICT(guild) DO UPDATE SET title=excluded.title,description=excluded.description,color=excluded.color,footer=excluded.footer,style=excluded.style').run(interaction.guildId,title,description,c,footer,style);await interaction.update(panel(db,interaction.guildId));return;}
  if(interaction.isStringSelectMenu()&&interaction.customId==='application:select'){const form=db.prepare('SELECT * FROM application_forms WHERE guild=? AND id=?').get(interaction.guildId,interaction.values[0]);if(!form)return interaction.reply({content:'❌ Application no longer exists.',ephemeral:true});return start(interaction,db,form);}
  if(interaction.isButton()&&interaction.customId.startsWith('application:select:')){const id=interaction.customId.slice('application:select:'.length),form=db.prepare('SELECT * FROM application_forms WHERE guild=? AND id=?').get(interaction.guildId,id);if(!form)return interaction.reply({content:'❌ Application no longer exists.',ephemeral:true});return start(interaction,db,form);}
  if(interaction.isButton()&&interaction.customId==='application:open')return start(interaction,db,ensureDefault(db,interaction.guildId));
  if(interaction.isModalSubmit()&&interaction.customId.startsWith('application:submit:')){const formId=interaction.customId.split(':').slice(2).join(':'),form=db.prepare('SELECT * FROM application_forms WHERE guild=? AND id=?').get(interaction.guildId,formId);if(!form)return interaction.reply({content:'❌ Application no longer exists.',ephemeral:true});return submit(interaction,db,form);}
  if(interaction.isButton()&&interaction.customId.startsWith('application:')){const [,action,id]=interaction.customId.split(':');if(!['accept','deny','hold'].includes(action))return false;const form=db.prepare('SELECT * FROM application_forms WHERE guild=? AND id=(SELECT form_id FROM applications WHERE id=?)').get(interaction.guildId,id);db.prepare('UPDATE applications SET status=?,reviewer=? WHERE guild=? AND id=?').run(action,interaction.user.id,interaction.guildId,id);if(action==='accept'&&form?.accept_role){const member=await interaction.guild.members.fetch((db.prepare('SELECT user FROM applications WHERE id=?').get(id)||{}).user||'').catch(()=>null);const role=interaction.guild.roles.cache.get(form.accept_role);if(member&&role)await member.roles.add(role).catch(()=>{});}return interaction.reply(`Application #${id}: **${action}** by ${interaction.user}.`);}
  return false;
}
module.exports={init,ensureDefault,ensurePanel,panel,handle};
