const { joinVoiceChannel, createAudioPlayer, createAudioResource, AudioPlayerStatus, NoSubscriberBehavior, VoiceConnectionStatus, entersState } = require('@discordjs/voice');
const play = require('play-dl');
const queues = new Map();
function getQueue(guildId){if(!queues.has(guildId))queues.set(guildId,{items:[],index:0,player:null,connection:null,text:null,volume:0.75,bound:false,nowPlaying:null});return queues.get(guildId);}
async function connect(i,q){const vc=i.member?.voice?.channel;if(!vc)throw new Error('Join a voice channel first.');const me=i.guild.members.me;if(!me?.permissionsIn(vc).has('Connect')||!me.permissionsIn(vc).has('Speak'))throw new Error('I need Connect and Speak permission in that voice channel.');if(!q.connection||q.connection.joinConfig.channelId!==vc.id){q.connection=joinVoiceChannel({guildId:i.guild.id,channelId:vc.id,adapterCreator:i.guild.voiceAdapterCreator,selfDeaf:true});await entersState(q.connection,VoiceConnectionStatus.Ready,15000);}if(!q.player)q.player=createAudioPlayer({behavior:{noSubscriber:NoSubscriberBehavior.Pause}});q.connection.subscribe(q.player);if(!q.bound){q.bound=true;q.player.on(AudioPlayerStatus.Idle,()=>{q.index++;playNext(i.guild).catch(console.error);});q.player.on('error',err=>{console.error('Music player error:',err);q.index++;playNext(i.guild).catch(console.error);});}}
async function resolve(query){const results=await play.search(query,{limit:1,source:{youtube:'video'}});if(!results.length)throw new Error('No result found.');const r=results[0];return{title:r.title||'Unknown title',url:r.url,duration:r.durationRaw||'unknown'};}
async function playNext(guild){const q=queues.get(guild.id);if(!q||q.index>=q.items.length){if(q?.text)q.text.send('⏹️ Queue finished.').catch(()=>{});return;}const item=q.items[q.index];try{const stream=await play.stream(item.url,{discordPlayerCompatibility:true,quality:2});const resource=createAudioResource(stream.stream,{inputType:stream.type,inlineVolume:true});resource.volume?.setVolume(q.volume);q.player.play(resource);q.nowPlaying=item;q.text?.send(`🎵 Now playing **${item.title}**`).catch(()=>{});}catch(e){q.text?.send(`❌ Could not play **${item.title}**: ${e.message}`).catch(()=>{});q.index++;return playNext(guild);}}
async function handle(i,name){if(!i.guild){await i.reply({content:'Music commands can only be used in a server.',ephemeral:true});return true;}const q=getQueue(i.guild.id);q.text=i.channel;try{if(name==='play'){const query=i.options.getString('query')||i.options.getString('song')||i.options.getString('url')||i.options.getString('search');if(!query){await i.reply({content:'Give me a song name or URL.',ephemeral:true});return true;}await connect(i,q);const item=await resolve(query);const wasIdle=!q.player.state||q.player.state.status===AudioPlayerStatus.Idle;q.items.push(item);await i.reply(`🎶 Added **${item.title}** to the queue.`);if(wasIdle)await playNext(i.guild);return true;}if(name==='pause'){q.player?.pause();await i.reply('⏸️ Paused.');return true;}if(name==='resume'){q.player?.unpause();await i.reply('▶️ Resumed.');return true;}if(name==='skip'){if(!q.player){await i.reply('Nothing is playing.');return true;}q.player.stop(true);await i.reply('⏭️ Skipped.');return true;}if(name==='stop'){q.items=[];q.index=0;q.nowPlaying=null;q.player?.stop(true);q.connection?.destroy();q.connection=null;await i.reply('⏹️ Stopped and cleared the queue.');return true;}if(name==='queue'){const pending=q.items.slice(q.index).map((x,n)=>`${n+1}. **${x.title}**`).slice(0,15);await i.reply(pending.length?`🎵 **Queue**\n${pending.join('\n')}`:'Queue is empty.');return true;}if(name==='nowplaying'){await i.reply(q.nowPlaying?`🎵 **Now playing:** ${q.nowPlaying.title}`:'Nothing is playing.');return true;}if(name==='volume'){const v=i.options.getInteger('percent')??i.options.getInteger('volume');if(v==null){await i.reply(`🔊 Volume: **${Math.round(q.volume*100)}%**`);return true;}q.volume=Math.max(0,Math.min(100,v))/100;await i.reply(`🔊 Volume set to **${v}%**.`);return true;}if(name==='loop'){await i.reply('🔁 Loop control is reserved for the next music update.');return true;}}catch(e){if(!i.replied&&!i.deferred)await i.reply({content:`❌ ${e.message}`,ephemeral:true}).catch(()=>{});return true;}return false;}
module.exports={handle,queues};
