const {ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,ChannelType,PermissionFlagsBits,EmbedBuilder}=require('discord.js');
const DEFAULT='general';
const COLORS={blue:0x5865f2,green:0x57f287,red:0xed4245,yellow:0xfee75c,purple:0x9b59b6};
function init(db){
  const cols=db.prepare('PRAGMA table_info(tickets)').all().map(x=>x.name);
  if(cols.length&&(!cols.includes('category_id')||!cols.includes('status'))){db.exec('ALTER TABLE tickets RENAME TO tickets_legacy');}
  db.exec(`CREATE TABLE IF NOT EXISTS ticket_categories(guild TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,emoji TEXT DEFAULT '🎫',category TEXT,staff_role TEXT,log_channel TEXT,transcript_channel TEXT,limit_per_user INTEGER DEFAULT 1,form_json TEXT DEFAULT '[]',panel_json TEXT DEFAULT '{}',PRIMARY KEY(guild,id));CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,guild TEXT,user TEXT,channel TEXT UNIQUE,category_id TEXT,claimed_by TEXT,status TEXT DEFAULT 'open',created INTEGER);CREATE TABLE IF NOT EXISTS ticket_panels(guild TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT DEFAULT '',color TEXT DEFAULT '5865f2',footer TEXT DEFAULT '',style TEXT DEFAULT 'dropdown');`);
  const legacy=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='tickets_legacy'").get();
  if(legacy){const rows=db.prepare('SELECT guild,user,channel,created FROM tickets_legacy').all();const ins=db.prepare('INSERT OR IGNORE INTO tickets(guild,user,channel,category_id,status,created) VALUES(?,?,?,?,?,?)');for(const r of rows)ins.run(r.guild,r.user,r.channel,DEFAULT,'open',r.created);db.exec('DROP TABLE tickets_legacy');}
}
function ensureGeneral(db,guild){let c=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(guild,DEFAULT);if(!c){db.prepare('INSERT INTO ticket_categories(guild,id,name,emoji,form_json,panel_json) VALUES(?,?,?,?,?,?)').run(guild,DEFAULT,'General Support','🎫','[]','{}');c=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(guild,DEFAULT);}return c;}
function ensurePanel(db,guild,defaults={}){let p=db.prepare('SELECT * FROM ticket_panels WHERE guild=?').get(guild);if(!p){db.prepare('INSERT INTO ticket_panels(guild,title,description,color,footer,style) VALUES(?,?,?,?,?,?)').run(guild,defaults.title||'🎫 Support Center',defaults.description||'Choose the category that best matches your request.',normalColor(defaults.color||'5865f2'),'','dropdown');p=db.prepare('SELECT * FROM ticket_panels WHERE guild=?').get(guild);}return p;}
function normalColor(v){let s=String(v||'5865f2').replace('#','').trim();return /^[0-9a-f]{6}$/i.test(s)?s.toUpperCase():'5865F2';}
function color(v){return parseInt(normalColor(v),16);}
function panel(db,guild,overrides={}){
  const saved=ensurePanel(db,guild,overrides),p={...saved,...overrides,color:normalColor(overrides.color||saved.color)};
  const cats=db.prepare('SELECT * FROM ticket_categories WHERE guild=? ORDER BY name').all(guild);const list=cats.length?cats:[ensureGeneral(db,guild)];
  const embed=new EmbedBuilder().setTitle(p.title||'🎫 Support Center').setDescription(p.description||'Choose a ticket category below.').setColor(color(p.color));if(p.footer)embed.setFooter({text:String(p.footer).slice(0,2048)});
  const components=[];
  if(String(p.style).toLowerCase()==='buttons'&&list.length<=20){for(let n=0;n<list.length;n+=5){components.push(new ActionRowBuilder().addComponents(...list.slice(n,n+5).map(c=>new ButtonBuilder().setCustomId(`ticket:category:${c.id}`).setLabel(String(c.name).slice(0,80)).setEmoji(c.emoji||'🎫').setStyle(ButtonStyle.Primary))));}}
  else components.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket:select').setPlaceholder('Select a ticket category').addOptions(list.slice(0,25).map(c=>({label:String(c.name).slice(0,100),value:c.id,emoji:c.emoji||'🎫',description:c.staff_role?'Staff-only support category':'Open a private support ticket'})))));
  if(components.length<5)components.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:editpanel').setLabel('Edit Panel').setEmoji('⚙️').setStyle(ButtonStyle.Secondary)));
  return {embeds:[embed],components};
}
function questionModal(cat){const qs=safeQuestions(cat.form_json);if(!qs.length)return null;const modal=new ModalBuilder().setCustomId(`ticket:form:${cat.id}`).setTitle(`${cat.name} • Ticket Questions`.slice(0,45));for(let n=0;n<Math.min(5,qs.length);n++){const q=qs[n],label=String(typeof q==='string'?q:q.label||`Question ${n+1}`).slice(0,45);modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(`q${n}`).setLabel(label).setStyle(q&&typeof q==='object'&&q.style==='short'?TextInputStyle.Short:TextInputStyle.Paragraph).setRequired(!(q&&typeof q==='object'&&q.required===false)).setMaxLength(1000)));}return modal;}
function safeQuestions(raw){try{const x=JSON.parse(raw||'[]');return Array.isArray(x)?x.slice(0,5):[];}catch{return[];}}
function transcript(channel,messages){const body=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(channel.name)}</title><style>body{font-family:Arial;background:#111;color:#eee;padding:24px}.m{padding:10px;border-bottom:1px solid #333}.a{font-weight:bold}.t{color:#999;font-size:12px}.c{white-space:pre-wrap}</style></head><body><h1>${esc(channel.name)}</h1>${messages.map(m=>`<div class="m"><span class="a">${esc(m.author?.tag||'Unknown')}</span> <span class="t">${new Date(m.createdTimestamp).toISOString()}</span><div class="c">${esc(m.content||'[embed/attachment]')}</div></div>`).join('')}</body></html>`;return Buffer.from(body);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function create(i,db,cat,answers=[]){cat=cat||ensureGeneral(db,i.guildId);const existing=db.prepare("SELECT channel FROM tickets WHERE guild=? AND user=? AND status='open'").get(i.guildId,i.user.id);if(existing)return i.reply({content:`You already have <#${existing.channel}> open.`,ephemeral:true});const staff=cat.staff_role?i.guild.roles.cache.get(cat.staff_role):null;const overwrites=[{id:i.guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}];if(staff)overwrites.push({id:staff.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const ch=await i.guild.channels.create({name:`${cat.name}-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,90),type:ChannelType.GuildText,parent:cat.category||undefined,permissionOverwrites:overwrites});db.prepare('INSERT INTO tickets(guild,user,channel,category_id,created) VALUES(?,?,?,?,?)').run(i.guildId,i.user.id,ch.id,cat.id,Date.now());const rows=[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:claim').setLabel('Claim').setEmoji('🙋').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:add').setLabel('Add Member').setEmoji('👤').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('ticket:close').setLabel('Close').setEmoji('🔒').setStyle(ButtonStyle.Danger))];const panelData=JSON.parse(cat.panel_json||'{}');const embeds=[new EmbedBuilder().setTitle(panelData.title||`🎫 ${cat.name}`).setDescription(panelData.description||'Support ticket created. Staff will assist you shortly.').setColor(color(panelData.color||'5865f2')).setTimestamp()];if(answers.length)embeds.push(new EmbedBuilder().setTitle('📋 Ticket Intake').setDescription(answers.map((x,n)=>`**${n+1}. ${x.question}**\n${x.answer}`).join('\n\n')).setColor(color(panelData.color||'5865f2')));await ch.send({content:`${staff||''} ${i.user}`,embeds,components:rows});return i.reply({content:`🎫 Created <#${ch.id}> in **${cat.name}**.`,ephemeral:true});}
async function close(i,db){const t=db.prepare('SELECT * FROM tickets WHERE channel=?').get(i.channelId);if(!t)return i.reply({content:'This is not a ticket.',ephemeral:true});await i.deferReply({ephemeral:true});const msgs=[];let last;for(let n=0;n<20;n++){const page=await i.channel.messages.fetch({limit:100,before:last}).catch(()=>new Map());if(!page.size)break;msgs.push(...page.values());last=page.last()?.id;if(page.size<100)break;}msgs.sort((a,b)=>a.createdTimestamp-b.createdTimestamp);const file=transcript(i.channel,msgs);const cat=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(i.guildId,t.category_id);const target=cat?.transcript_channel||cat?.log_channel;const log=target?i.guild.channels.cache.get(target):null;if(log)await log.send({content:`📄 Transcript • ${i.channel.name}`,files:[{attachment:file,name:`${i.channel.name}.html`}],embeds:[new EmbedBuilder().setTitle('🔒 Ticket Closed').setDescription(`Opened by <@${t.user}>\nClosed by ${i.user}\nCategory: ${cat?.name||t.category_id}`).setColor(0xed4245)]});db.prepare("UPDATE tickets SET status='closed' WHERE channel=?").run(i.channelId);await i.editReply('Transcript created. The ticket will close now.');setTimeout(()=>i.channel.delete().catch(()=>{}),1200);}
function editModal(db,guild){const p=ensurePanel(db,guild);return new ModalBuilder().setCustomId('ticket:editpanel:submit').setTitle('Edit Ticket Panel').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('title').setLabel('Panel title').setStyle(TextInputStyle.Short).setValue(String(p.title||'').slice(0,256)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Panel description').setStyle(TextInputStyle.Paragraph).setValue(String(p.description||'').slice(0,4000)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('color').setLabel('Embed color (HEX)').setStyle(TextInputStyle.Short).setValue(normalColor(p.color)).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('footer').setLabel('Footer (optional)').setStyle(TextInputStyle.Short).setValue(String(p.footer||'').slice(0,2048)).setRequired(false)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('style').setLabel('Layout: dropdown or buttons').setStyle(TextInputStyle.Short).setValue(String(p.style||'dropdown')).setRequired(true)));}
function canManage(i){return !!(i.member?.permissions?.has(PermissionFlagsBits.Administrator)||i.member?.permissions?.has(PermissionFlagsBits.ManageGuild));}
async function handle(i,ctx){const {db}=ctx;
  if(i.isButton()&&i.customId==='ticket:editpanel'){if(!canManage(i))return i.reply({content:'⛔ Only server managers can edit ticket panels.',ephemeral:true});return i.showModal(editModal(db,i.guildId));}
  if(i.isModalSubmit()&&i.customId==='ticket:editpanel:submit'){if(!canManage(i))return i.reply({content:'⛔ Only server managers can edit ticket panels.',ephemeral:true});const title=i.fields.getTextInputValue('title'),description=i.fields.getTextInputValue('description'),c=normalColor(i.fields.getTextInputValue('color')),footer=i.fields.getTextInputValue('footer'),style=['buttons','dropdown'].includes(i.fields.getTextInputValue('style').toLowerCase())?i.fields.getTextInputValue('style').toLowerCase():'dropdown';db.prepare('INSERT INTO ticket_panels(guild,title,description,color,footer,style) VALUES(?,?,?,?,?,?) ON CONFLICT(guild) DO UPDATE SET title=excluded.title,description=excluded.description,color=excluded.color,footer=excluded.footer,style=excluded.style').run(i.guildId,title,description,c,footer,style);await i.update(panel(db,i.guildId));return;}
  if(i.isStringSelectMenu()&&i.customId==='ticket:select'){const cat=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(i.guildId,i.values[0]);if(!cat)return i.reply({content:'❌ Ticket category no longer exists.',ephemeral:true});const modal=questionModal(cat);if(modal)return i.showModal(modal);return create(i,db,cat);}
  if(i.isButton()&&i.customId.startsWith('ticket:category:')){const id=i.customId.split(':').slice(2).join(':'),cat=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(i.guildId,id);if(!cat)return i.reply({content:'❌ Ticket category no longer exists.',ephemeral:true});const modal=questionModal(cat);if(modal)return i.showModal(modal);return create(i,db,cat);}
  if(i.isModalSubmit()&&i.customId.startsWith('ticket:form:')){const id=i.customId.slice('ticket:form:'.length),cat=db.prepare('SELECT * FROM ticket_categories WHERE guild=? AND id=?').get(i.guildId,id);if(!cat)return i.reply({content:'❌ Ticket category no longer exists.',ephemeral:true});const qs=safeQuestions(cat.form_json),answers=qs.map((q,n)=>({question:typeof q==='string'?q:String(q.label||`Question ${n+1}`),answer:i.fields.getTextInputValue(`q${n}`)}));return create(i,db,cat,answers);}
  if(i.isButton()&&i.customId==='ticket:create')return create(i,db,ensureGeneral(db,i.guildId));
  if(i.isButton()&&i.customId==='ticket:close')return close(i,db);
  if(i.isButton()&&i.customId==='ticket:claim'){db.prepare('UPDATE tickets SET claimed_by=? WHERE channel=?').run(i.user.id,i.channelId);return i.reply(`🎫 Claimed by ${i.user}.`);}
  if(i.isButton()&&i.customId==='ticket:add'){const modal=new ModalBuilder().setCustomId('ticket:addmodal').setTitle('Add member').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('user').setLabel('User ID').setStyle(TextInputStyle.Short).setRequired(true)));return i.showModal(modal);}
  if(i.isModalSubmit()&&i.customId==='ticket:addmodal'){const id=i.fields.getTextInputValue('user');const m=await i.guild.members.fetch(id).catch(()=>null);if(!m)return i.reply({content:'Member not found.',ephemeral:true});await i.channel.permissionOverwrites.edit(m.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true});return i.reply(`Added ${m} to the ticket.`);}
  return false;
}
module.exports={init,ensureGeneral,ensurePanel,panel,handle,create,close};
