const { ChannelType, PermissionsBitField, EmbedBuilder } = require('discord.js');

function ensure(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS member_stats(guild TEXT,user TEXT,messages INTEGER DEFAULT 0,voice_seconds INTEGER DEFAULT 0,joins INTEGER DEFAULT 0,last_message INTEGER DEFAULT 0,PRIMARY KEY(guild,user));
    CREATE TABLE IF NOT EXISTS channel_stats(guild TEXT,channel TEXT,messages INTEGER DEFAULT 0,voice_seconds INTEGER DEFAULT 0,PRIMARY KEY(guild,channel));
    CREATE TABLE IF NOT EXISTS stat_events(id INTEGER PRIMARY KEY AUTOINCREMENT,guild TEXT,user TEXT,type TEXT,amount INTEGER DEFAULT 1,at INTEGER);
    CREATE TABLE IF NOT EXISTS stat_counters(guild TEXT PRIMARY KEY,category TEXT,channels TEXT);
  `);
}
const up=(db,sql,args)=>db.prepare(sql).run(...args);
function member(db,g,u){up(db,'INSERT OR IGNORE INTO member_stats(guild,user) VALUES(?,?)',[g,u]);return db.prepare('SELECT * FROM member_stats WHERE guild=? AND user=?').get(g,u)}
function recordMessage(db,g,u,c){member(db,g,u);up(db,'UPDATE member_stats SET messages=messages+1,last_message=? WHERE guild=? AND user=?',[Date.now(),g,u]);up(db,'INSERT OR IGNORE INTO channel_stats(guild,channel) VALUES(?,?)',[g,c]);up(db,'UPDATE channel_stats SET messages=messages+1 WHERE guild=? AND channel=?',[g,c]);up(db,'INSERT INTO stat_events(guild,user,type,amount,at) VALUES(?,?,?,?,?)',[g,u,'message',1,Date.now()])}
function addVoice(db,g,u,c,seconds){member(db,g,u);up(db,'UPDATE member_stats SET voice_seconds=voice_seconds+? WHERE guild=? AND user=?',[seconds,g,u]);up(db,'INSERT OR IGNORE INTO channel_stats(guild,channel) VALUES(?,?)',[g,c]);up(db,'UPDATE channel_stats SET voice_seconds=voice_seconds+? WHERE guild=? AND channel=?',[seconds,g,c]);up(db,'INSERT INTO stat_events(guild,user,type,amount,at) VALUES(?,?,?,?,?)',[g,u,'voice',seconds,Date.now()])}
function format(s){s=Number(s)||0;const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return `${h}h ${m}m`}
function serverEmbed(guild,db){const msgs=db.prepare('SELECT COALESCE(SUM(messages),0) n FROM member_stats WHERE guild=?').get(guild.id).n;const voice=db.prepare('SELECT COALESCE(SUM(voice_seconds),0) n FROM member_stats WHERE guild=?').get(guild.id).n;return new EmbedBuilder().setTitle(`📊 ${guild.name} Statistics`).addFields({name:'Members',value:String(guild.memberCount),inline:true},{name:'Bots',value:String(guild.members.cache.filter(m=>m.user.bot).size),inline:true},{name:'Messages tracked',value:String(msgs),inline:true},{name:'Voice tracked',value:format(voice),inline:true},{name:'Channels',value:String(guild.channels.cache.size),inline:true},{name:'Roles',value:String(guild.roles.cache.size),inline:true}).setColor(0x5865f2).setTimestamp()}
async function command(i,n,db){
 if(n==='stats'||n==='serverstats') return i.reply({embeds:[serverEmbed(i.guild,db)]});
 if(n==='memberstats'||n==='mystats'||n==='userstats'||n==='me'){const u=i.options?.getUser?.('user')||i.user,r=member(db,i.guildId,u.id);return i.reply({embeds:[new EmbedBuilder().setTitle(`📈 ${u.username} Statistics`).setDescription(`Messages: **${r.messages}**\nVoice time: **${format(r.voice_seconds)}**\nLast message: ${r.last_message?`<t:${Math.floor(r.last_message/1000)}:R>`:'Never'}`).setThumbnail(u.displayAvatarURL()).setColor(0x5865f2)]})}
 if(n==='statleaderboard'||n==='statlb'||n==='topstats'||n==='top'){const rows=db.prepare('SELECT user,messages,voice_seconds FROM member_stats WHERE guild=? ORDER BY messages DESC LIMIT 10').all(i.guildId);return i.reply({embeds:[new EmbedBuilder().setTitle('🏆 Activity Leaderboard').setDescription(rows.length?rows.map((r,k)=>`**${k+1}.** <@${r.user}> — ${r.messages} messages • ${format(r.voice_seconds)}`).join('\n'):'No tracked activity yet.').setColor(0x5865f2)]})}
 if(n==='counter'||n==='counters'||n==='statcounter'||n==='statcounters') return setupCounters(i,db);
 if(n==='statsreset'){if(!i.member.permissions.has(PermissionsBitField.Flags.ManageGuild))return i.reply({content:'Manage Server required.',ephemeral:true});db.prepare('DELETE FROM member_stats WHERE guild=?').run(i.guildId);db.prepare('DELETE FROM channel_stats WHERE guild=?').run(i.guildId);return i.reply('🧹 Statistics reset.')}
 return i.reply('📊 Statistics module ready.');
}
async function setupCounters(i,db){if(!i.member.permissions.has(PermissionsBitField.Flags.ManageChannels))return i.reply({content:'Manage Channels required.',ephemeral:true});const cat=await i.guild.channels.create({name:'📊 SERVER STATS',type:ChannelType.GuildCategory});const specs=[['members','Members'],['bots','Bots'],['channels','Channels'],['roles','Roles'],['online','Online'],['boosts','Boosts']];const ids=[];for(const [key,label] of specs){const c=await i.guild.channels.create({name:`${label}: ${counterValue(i.guild,key)}`,type:ChannelType.GuildVoice,parent:cat.id,permissionOverwrites:[{id:i.guild.roles.everyone.id,deny:[PermissionsBitField.Flags.Connect]}]});ids.push(`${key}:${c.id}`)}db.prepare('INSERT INTO stat_counters(guild,category,channels) VALUES(?,?,?) ON CONFLICT(guild) DO UPDATE SET category=excluded.category,channels=excluded.channels').run(i.guildId,cat.id,ids.join(','));return i.reply(`📊 Created ${specs.length} stat counters in ${cat}.`)}
function counterValue(g,k){if(k==='members')return g.memberCount;if(k==='bots')return g.members.cache.filter(m=>m.user.bot).size;if(k==='channels')return g.channels.cache.size;if(k==='roles')return g.roles.cache.size;if(k==='online')return g.members.cache.filter(m=>m.presence?.status==='online').size;if(k==='boosts')return g.premiumSubscriptionCount||0;return 0}
async function updateCounters(guild,db){const row=db.prepare('SELECT * FROM stat_counters WHERE guild=?').get(guild.id);if(!row)return;for(const item of row.channels.split(',').filter(Boolean)){const [key,id]=item.split(':');const c=guild.channels.cache.get(id);if(c)await c.setName(`${key[0].toUpperCase()+key.slice(1)}: ${counterValue(guild,key)}`).catch(()=>{})}}
module.exports={ensure,recordMessage,addVoice,command,updateCounters,member};
