const fs=require('fs');
const path=require('path');
const {ChannelType,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder}=require('discord.js');
module.exports=function(client,prefix='.'){
 const P=prefix||'.',FILE=path.join(process.cwd(),'data','enhancements.json');let db={};try{db=JSON.parse(fs.readFileSync(FILE,'utf8')||'{}')}catch{db={}};
 const save=()=>fs.writeFileSync(FILE,JSON.stringify(db,null,2));const g=id=>db[id]||(db[id]={afk:{},logs:{}});const clean=(x,n=850)=>String(x??'').replace(/`/g,'').slice(0,n);const E=(t,d)=>new EmbedBuilder().setTitle(t).setDescription(d).setColor(0x5865f2).setTimestamp();
 const cats={home:['help','ping','botinfo','invite'],music:['play','p','join','connect','leave','disconnect','pause','resume','unpause','skip','next','stop','queue','q','nowplaying','np','current','volume','vol','loop','repeat','shuffle','remove','move','clearqueue','musichelp'],moderation:['kick','ban','unban','timeout','untimeout','warn','warnings','clearwarnings','purge','lock','unlock','slowmode','nick','lockdown','unlockdown','softban','unwarn','massrole'],security:['automod','antiraid','antinuke','security','filter','verify'],logging:['logsetup','logsettings','logevents','logtest','setlog','logdisable'],leveling:['level','rank','leaderboard','xp','setxp','leveling','reward','rewards'],economy:['balance','daily','work','deposit','withdraw','pay','economy','richlist'],tickets:['ticket','ticket-panel','open','close','claim','unclaim','ticket-setup'],roles:['role','autorole','reactionrole','levelrole','roleall'],welcome:['welcome','setwelcome','setwelcome-message','goodbye'],voice:['tempvoice','voice'],starboard:['starboard'],afk:['afk'],applications:['apply','applications','application-setup','application-questions'],announcements:['announce','say','embed','poll','announce-embed'],utility:['serverinfo','userinfo','avatar','roleinfo','channelinfo','membercount','servericon','config','prefix','enable','disable','permissions','channel'],fun:['8ball','eightball','coinflip','roll','choose','ship','rate','reverse'],custom:['customcommand','cc','cc-delete','cc-list'],reminders:['remind','reminders']};
 const names={home:'🏠 Home',music:'🎧 Music',moderation:'🛡️ Moderation',security:'🔐 Security',logging:'📋 Logging',leveling:'📈 Leveling',economy:'💰 Economy',tickets:'🎫 Tickets',roles:'🎭 Roles',welcome:'👋 Welcome',voice:'🔊 Voice',starboard:'⭐ Starboard',afk:'💤 AFK',applications:'📝 Applications',announcements:'📢 Announcements',utility:'🛠️ Utility',fun:'🎉 Fun',custom:'⚙️ Custom',reminders:'⏰ Reminders'};
 function help(cat='home'){if(!cats[cat])cat='home';const list=cats[cat];if(cat==='home'){return {embeds:[E('✨ LIGHTCORE • HELP CENTER',`**Prefix:** \`${P}\`\n\n${Object.keys(cats).map(k=>`> **${names[k]}**  •  \`${P}help ${k}\``).join('\n')}\n\n> 💫 Choose a category below.`)],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('lc_help_final').setPlaceholder('✨ Browse all features').addOptions(Object.keys(cats).map(k=>({label:names[k].replace(/^\S+\s/,''),value:k,emoji:names[k].split(' ')[0]}))))]};}return {embeds:[E(`${names[cat]} • COMMANDS`,`> ✦ **${list.length}** commands\n\n${list.map(x=>`\`${P}${x}\``).join('  •  ')}`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('lc_help_final_home').setLabel('Help Home').setEmoji('🏠').setStyle(ButtonStyle.Secondary))]};}
 const LT=['messages','members','moderation','roles','channels','voice','server','invites','threads','automod','boosts'];const LN={messages:'💬・message-logs',members:'👥・member-logs',moderation:'🛡️・moderation-logs',roles:'🎭・role-logs',channels:'📝・channel-logs',voice:'🔊・voice-logs',server:'⚙️・server-logs',invites:'🔗・invite-logs',threads:'🧵・thread-logs',automod:'🤖・automod-logs',boosts:'🚀・boost-logs'};const LTITLE={messages:'Message Logs',members:'Member Logs',moderation:'Moderation Logs',roles:'Role Logs',channels:'Channel Logs',voice:'Voice Logs',server:'Server Logs',invites:'Invite Logs',threads:'Thread Logs',automod:'Automod Logs',boosts:'Boost Logs'};
 const logs=x=>{const z=g(x.id);z.logs||={};return z.logs;};
 async function channel(server,type){const l=logs(server);let cat=l.category?server.channels.cache.get(l.category):null;if(!cat)cat=server.channels.cache.find(x=>x.type===ChannelType.GuildCategory&&x.name==='📋・LOGS');if(!cat)cat=await server.channels.create({name:'📋・LOGS',type:ChannelType.GuildCategory});l.category=cat.id;let ch=l[type]?server.channels.cache.get(l[type]):null;if(!ch)ch=server.channels.cache.find(x=>x.parentId===cat.id&&x.name===LN[type]);if(!ch)ch=await server.channels.create({name:LN[type],type:ChannelType.GuildText,parent:cat.id});l[type]=ch.id;save();return ch;}
 async function write(server,type,title,text){const l=logs(server),id=l[type];if(!id)return;const ch=client.channels.cache.get(id);if(ch?.isTextBased())await ch.send({embeds:[E(title,text)]}).catch(()=>{});}
 async function command(m,c,a){if(c==='help'||c==='h')return m.reply(help((a[0]||'home').toLowerCase()));if(c==='musichelp'||c==='music')return m.reply(help('music'));if(c==='afk'){const z=g(m.guild.id);z.afk[m.author.id]={reason:clean(a.join(' '),180)||'AFK',at:Date.now()};save();return m.reply({embeds:[E('💤 AFK MODE ENABLED',`> 🌙 **${m.author} is now AFK**\n>\n> **Reason:** ${z.afk[m.author.id].reason}\n> **Since:** <t:${Math.floor(Date.now()/1000)}:R>`)]});}if(c==='logsetup'){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply('❌ Manage Server required.');const one=(a[0]||'').toLowerCase(),types=LT.includes(one)?[one]:LT;for(const t of types)await channel(m.guild,t);const l=logs(m.guild);return m.reply({embeds:[E('📋 LOGGING SYSTEM READY',`${types.length===LT.length?'✨ Full logging':'🎯 Single log'} setup complete.\n\n${types.map(t=>`${LN[t]} → <#${l[t]}>`).join('\n')}\n\nUse \`${P}setlog <type> #channel\` to change one stream.`)]});}if(c==='setlog'){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply('❌ Manage Server required.');const t=(a[0]||'').toLowerCase(),ch=m.mentions.channels.first();if(!LT.includes(t)||!ch)return m.reply(`Usage: ${P}setlog <${LT.join('|')}> #channel`);logs(m.guild)[t]=ch.id;save();return m.reply(`✅ **${LTITLE[t]}** → ${ch}`);}if(c==='logdisable'){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply('❌ Manage Server required.');const t=(a[0]||'').toLowerCase();if(!LT.includes(t))return m.reply(`Usage: ${P}logdisable <${LT.join('|')}>`);delete logs(m.guild)[t];save();return m.reply(`🔕 **${LTITLE[t]}** disabled.`);}if(c==='logsettings')return m.reply({embeds:[E('📋 LOG SETTINGS',LT.map(t=>`${LN[t]} • ${logs(m.guild)[t]?`<#${logs(m.guild)[t]}>`:'OFF'}`).join('\n'))]});if(c==='logevents')return m.reply({embeds:[E('📚 LOG EVENTS',LT.map(t=>`**${t}** — ${LTITLE[t]}`).join('\n'))]});if(c==='logtest'){for(const t of LT)await write(m.guild,t,'🧪 Log Test',`Test event for **${LTITLE[t]}**.`);return m.reply('✅ Log test sent to all configured streams.');}return false;}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;const z=g(m.guild.id);for(const id of m.mentions.users.keys()){if(id!==m.author.id&&z.afk[id]){const x=z.afk[id];await m.reply({embeds:[E('💤 USER IS AFK',`> 👤 <@${id}> is AFK.\n> 💬 **Reason:** ${clean(x.reason,180)}\n> ⏱️ **Since:** <t:${Math.floor(x.at/1000)}:R>`)]}).catch(()=>{});break;}}if(z.afk[m.author.id]&&!m.content.startsWith(P)){delete z.afk[m.author.id];save();await m.reply({embeds:[E('👋 WELCOME BACK',`> ✨ Welcome back ${m.author}! Your AFK status has been removed.`)]}).catch(()=>{});}if(!m.content.startsWith(P))return old(m);const p=m.content.slice(P.length).trim().split(/\s+/),c=(p.shift()||'').toLowerCase();if(!(await command(m,c,p)))return old(m);}catch(e){console.error('[FINAL ENHANCEMENTS]',e);}});}
 const evs=['messageDelete','messageUpdate','messageDeleteBulk','guildMemberAdd','guildMemberRemove','guildMemberUpdate','guildBanAdd','guildBanRemove','roleCreate','roleDelete','channelCreate','channelDelete','channelUpdate','voiceStateUpdate','inviteCreate','threadCreate','threadDelete'];
 for(const ev of evs){for(const fn of client.listeners(ev)){const s=Function.prototype.toString.call(fn);if(s.includes("log(m.guild")||s.includes("log(n.guild")||s.includes("log(ch.guild")||s.includes("log(b.guild")||s.includes("log(r.guild")||s.includes("log(c.guild")||s.includes("log(t.guild"))client.removeListener(ev,fn);}}
 client.on('messageDelete',m=>{if(m.guild&&!m.author?.bot)write(m.guild,'messages','🗑️ Message Deleted',`**Author:** ${m.author||'Unknown'}\n**Channel:** ${m.channel}\n**Content:** ${clean(m.content)||'Unavailable'}`)});
 client.on('messageUpdate',(o,n)=>{if(n.guild&&!n.author?.bot&&o.content!==n.content)write(n.guild,'messages','✏️ Message Edited',`**Author:** ${n.author}\n**Channel:** ${n.channel}\n**Before:** ${clean(o.content)||'Unavailable'}\n**After:** ${clean(n.content)||'Unavailable'}`)});
 client.on('messageDeleteBulk',(c,ch)=>write(ch.guild,'messages','🧹 Bulk Delete',`**Channel:** ${ch}\n**Messages:** ${c.size}`));
 client.on('guildMemberAdd',m=>write(m.guild,'members','📥 Member Joined',`**User:** ${m.user}\n**ID:** \`${m.id}\``));client.on('guildMemberRemove',m=>write(m.guild,'members','📤 Member Left',`**User:** ${m.user}\n**ID:** \`${m.id}\``));client.on('guildMemberUpdate',(o,n)=>{const a=[];if(o.nickname!==n.nickname)a.push(`Nickname: **${o.nickname||'none'}** → **${n.nickname||'none'}**`);if(o.roles.cache.size!==n.roles.cache.size)a.push(`Roles: **${o.roles.cache.size}** → **${n.roles.cache.size}**`);if(a.length)write(n.guild,'members','📝 Member Updated',`**User:** ${n.user}\n${a.join('\n')}`)});client.on('guildBanAdd',b=>write(b.guild,'moderation','🔨 Member Banned',`**User:** ${b.user}`));client.on('guildBanRemove',b=>write(b.guild,'moderation','🔓 Member Unbanned',`**User:** ${b.user}`));client.on('roleCreate',r=>write(r.guild,'roles','➕ Role Created',`**Role:** ${r}`));client.on('roleDelete',r=>write(r.guild,'roles','🗑️ Role Deleted',`**Role:** ${r.name}\n**ID:** \`${r.id}\``));client.on('channelCreate',c=>write(c.guild,'channels','➕ Channel Created',`**Channel:** ${c}\n**Type:** ${c.type}`));client.on('channelDelete',c=>write(c.guild,'channels','🗑️ Channel Deleted',`**Name:** ${c.name}\n**ID:** \`${c.id}\``));client.on('channelUpdate',(o,n)=>write(n.guild,'channels','📝 Channel Updated',`**Channel:** ${n}`));client.on('voiceStateUpdate',(o,n)=>{if(o.channelId!==n.channelId)write(n.guild,'voice','🔊 Voice State',`**User:** ${n.member?.user||o.member?.user}\n**From:** ${o.channel?.name||'None'}\n**To:** ${n.channel?.name||'None'}`)});client.on('inviteCreate',i=>write(i.guild,'invites','🔗 Invite Created',`**Code:** \`${i.code}\`\n**Channel:** ${i.channel}`));client.on('threadCreate',t=>write(t.guild,'threads','🧵 Thread Created',`**Thread:** ${t}`));client.on('threadDelete',t=>write(t.guild,'threads','🗑️ Thread Deleted',`**Thread:** ${t.name}\n**ID:** \`${t.id}\``));client.on('guildMemberUpdate',(o,n)=>{if(n.premiumSince&&!o.premiumSince)write(n.guild,'boosts','🚀 Server Boost',`**User:** ${n.user} boosted the server.`)});
 client.on('interactionCreate',async i=>{try{if(i.isStringSelectMenu()&&i.customId==='lc_help_final')return i.update(help(i.values[0]));if(i.isButton()&&i.customId==='lc_help_final_home')return i.update(help('home'));}catch(e){console.error('[HELP FINAL]',e)}});
 console.log('[FINAL] Help + AFK + per-event logging online.');
};
