const fs=require('fs');const path=require('path');
const attachEmbedTheme=require('./embed-theme.js');const attach=require('./feature-pack.js');const attachServerFeatures=require('./server-features.js');const attachNotifier=require('./notifier.js');const attachUltimate=require('./ultimate-features.js');const attachFinalSuite=require('./final-suite.js');const attachMusic=require('./music.js');const attachCounterAutosetup=require('./counter-autosetup.js');const attachTemplateVoice=require('./template-voice.js');const attachRaidShield=require('./raid-shield.js');const attachGlobalEconomy=require('./global-economy.js');const attachCommunitySuite=require('./community-suite.js');const attachManagementSuite=require('./management-suite.js');const attachMembersStats=require('./members-stats.js');const attachTicketSuite=require('./ticket-suite-v2.js');const attachCoreUtilities=require('./core-utilities.js');const attachHelpFinal=require('./help-final.js');const attachAdvancedLogging=require('./advanced-logging.js');const attachEasyCommands=require('./easy-commands.js');
module.exports=function loadFeaturePack(bot){
 if(!bot?.client)throw new Error('LightCore client is unavailable.');
 attachEmbedTheme(bot.client);
 const dataDir=path.join(process.cwd(),'data');const file=path.join(dataDir,'database.json');if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,'{}');
 let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{db={}};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));const fresh=()=>({featurePack:{ticketCategory:null,ticketStaffRole:null,rr:{},temp:{category:null,creator:null},welcome:null,goodbye:null,filters:[],autorole:null,raid:{enabled:false},nuke:{enabled:false}},custom:{},reminders:[]});const gd=id=>{const d=db[id]||(db[id]=fresh());const f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];return d;};
 attach(bot.client,db,save,gd,'.');attachServerFeatures(bot.client,'.');attachNotifier(bot.client,'.');attachUltimate(bot.client,'.');attachFinalSuite(bot.client,'.');attachMusic(bot.client,'.');attachCounterAutosetup(bot.client,'.');attachTemplateVoice(bot.client,'.');attachRaidShield(bot.client,'.');attachGlobalEconomy(bot.client,'.');attachCommunitySuite(bot.client,'.');attachManagementSuite(bot.client,'.');attachMembersStats(bot.client,'.');attachTicketSuite(bot.client,'.');attachCoreUtilities(bot.client,'.');attachHelpFinal(bot.client,'.');attachAdvancedLogging(bot.client,'.');attachEasyCommands(bot.client,'.');
 const listeners=bot.client.listeners('messageCreate');if(listeners.length>1){const outer=listeners[listeners.length-1];for(const listener of listeners)if(listener!==outer)bot.client.removeListener('messageCreate',listener)}
 console.log(`[FEATURES] Full command stack loaded | prefix: . | guided tickets + advanced Zeon-style logging + music + member stats + ordered help | message handlers: ${bot.client.listenerCount('messageCreate')}`);
};