const fs=require('fs'),path=require('path');
const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,PermissionFlagsBits}=require('discord.js');
module.exports=function attachGiveaways(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','giveaways.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));const arr=g=>(db[g]??=[]);const parse=t=>{const m=String(t||'').match(/^(\d+)\s*(s|m|h|d|w)$/i);if(!m)return 0;return Number(m[1])*({s:1000,m:60000,h:3600000,d:86400000,w:604800000}[m[2].toLowerCase()])};const pick=a=>a.sort(()=>Math.random()-.5).slice(0,Math.max(1,a.length));
 const embed=(x,ended=false)=>new EmbedBuilder().setTitle(ended?'🎉 Giveaway Ended':'🎉 GIVEAWAY').setDescription(`**Prize:** ${x.prize}\n**Winners:** ${x.winners}\n**Hosted by:** <@${x.host}>\n\n${ended?'🏁 Giveaway ended. Winners: '+(x.winnerIds?.map(id=>`<@${id}>`).join(', ')||'No valid winners.'):`🎟️ Entries: **${x.entries.length}**\n\nClick **🎉 Enter** to join!\nEnds <t:${Math.floor(x.end/1000)}:R>`}`).setColor(ended?0x57f287:0x5865f2).setTimestamp();
 const row=id=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`lc_gw_enter:${id}`).setLabel('🎉 Enter').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`lc_gw_leave:${id}`).setLabel('🚪 Leave').setStyle(ButtonStyle.Secondary));
 async function finish(x,guild){if(x.ended)return;const ch=guild.channels.cache.get(x.channel),m=ch&&await ch.messages.fetch(x.message).catch(()=>null);x.ended=true;x.winnerIds=pick([...new Set(x.entries)]).slice(0,x.winners);save();if(m)await m.edit({embeds:[embed(x,true)],components:[]}).catch(()=>{});if(ch)await ch.send(`🎉 **Giveaway Winner${x.winnerIds.length===1?'':'s'}:** ${x.winnerIds.map(id=>`<@${id}>`).join(', ')||'No valid entries'} — **${x.prize}**`).catch(()=>{});}
 setInterval(async()=>{for(const [gid,list] of Object.entries(db))for(const x of list)if(!x.ended&&x.end<=Date.now()){const g=client.guilds.cache.get(gid);if(g)await finish(x,g)}save()},5000).unref();
 client.on('messageCreate',async m=>{if(m.author.bot||!m.guild||!m.content.startsWith(P))return;const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(!['giveaway','gstart','gend','greroll','glist'].includes(c))return;if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id&&['giveaway','gstart','gend','greroll'].includes(c))return m.reply('❌ Manage Server required.');if(c==='glist'){const active=arr(m.guild.id).filter(x=>!x.ended);return m.reply({embeds:[new EmbedBuilder().setTitle('🎉 Active Giveaways').setDescription(active.length?active.map(x=>`• **${x.prize}** — <#${x.channel}> — <t:${Math.floor(x.end/1000)}:R> — ID \`${x.id}\``).join('\n'):'No active giveaways.')]});}if(c==='gend'){const x=arr(m.guild.id).find(x=>x.id===a[0]&&!x.ended);if(!x)return m.reply('❌ Giveaway not found.');await finish(x,m.guild);return m.reply('✅ Giveaway ended.');}if(c==='greroll'){const x=arr(m.guild.id).find(x=>x.id===a[0]);if(!x)return m.reply('❌ Giveaway not found.');const winners=pick([...new Set(x.entries)]).slice(0,x.winners);return m.reply(`🎉 New winner${winners.length===1?'':'s'}: ${winners.map(id=>`<@${id}>`).join(', ')||'No valid entries.'}`);}const ms=parse(a[0]);const winners=Math.max(1,Number(a[1])||1);const prize=a.slice(2).join(' ');if(!ms||!prize)return m.reply(`Usage: ${P}giveaway <10m|1h|1d> <winners> <prize>`);const x={id:Date.now().toString(36),channel:m.channel.id,message:null,host:m.author.id,winners,prize,entries:[],end:Date.now()+ms,ended:false};const msg=await m.channel.send({embeds:[embed(x)],components:[row(x.id)]});x.message=msg.id;arr(m.guild.id).push(x);save();return m.reply(`✅ Giveaway started. ID: \`${x.id}\``)});
 client.on('interactionCreate',async i=>{if(!i.isButton()||!i.customId.startsWith('lc_gw_'))return;const [action,id]=i.customId.split(':');const x=arr(i.guild.id).find(x=>x.id===id&&!x.ended);if(!x)return i.reply({content:'❌ This giveaway has ended.',ephemeral:true});if(action==='lc_gw_enter'){if(x.entries.includes(i.user.id))return i.reply({content:'You are already entered.',ephemeral:true});x.entries.push(i.user.id);save();return i.reply({content:'🎉 You entered the giveaway!',ephemeral:true});}x.entries=x.entries.filter(id=>id!==i.user.id);save();return i.reply({content:'🚪 You left the giveaway.',ephemeral:true});});
 console.log('[GIVEAWAYS] Giveaway system loaded');
};