const {EmbedBuilder,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
module.exports=function(client,prefix='.'){
 const P=prefix||'.';
 const groups={home:['help','ping','uptime','botinfo','invite','support','serverinfo','membercount','userinfo','avatar','roleinfo','channelinfo','servericon'],moderation:['kick','ban','unban','softban','timeout','untimeout','warn','unwarn','warnings','clearwarnings','purge','lock','unlock','slowmode','nick','lockdown','unlockdown','massrole'],security:['automod','antiraid','antinuke','security','filter','filter-add','filter-remove','verify','honeypot'],logging:['logsetup','setlog','logdisable','logsettings','logevents','logtest','logreset'],leveling:['level','rank','xp','leaderboard','setxp','leveling','reward','rewards'],economy:['balance','bal','daily','work','beg','deposit','withdraw','pay','richlist','luck','eco'],music:['play','p','join','connect','leave','disconnect','pause','resume','unpause','skip','next','stop','queue','q','nowplaying','np','current','volume','vol','loop','repeat','shuffle','remove','move','clearqueue','musichelp'],tickets:['ticket','ticket setup','ticket panel','ticket categories','ticket addcategory','ticket editcategory','ticket delcategory','ticket editpanel title','ticket editpanel description','ticket editpanel color','ticket editpanel button','ticket open','ticket close','ticket claim','ticket unclaim','ticket add','ticket remove','ticket rename','ticket logs','ticket transcripts','application setup','application panel','application edit title','application edit description','application edit color','application edit button','application questions','application question add','application question remove','application question edit','apply'],giveaways:['giveaway','gcreate'],fun:['8ball','eightball','coinflip','roll','choose','ship','rate','cat','dog','joke','reverse'],counters:['counter','counter autosetup','counter setup','counter remove','counter update'],memberstats:['stats','stat','stats @user','serverstats','members','messages','messages @user','memberstats','membersstats'],notifications:['notifier add','notifier list','notifier remove','notifier enable','notifier disable','notifier test'],invites:['invites','invites-leaderboard','inviteconfig'],announcements:['announce','say','embed','embedhelp','poll','announce-embed'],roles:['role','role give','role remove','role duplicate','deleterole','autorole','reactionrole','levelrole','roleall'],channels:['channel create','channel duplicate','category delete'],welcome:['welcome','setwelcome','setwelcome-message','goodbye'],autoresponder:['autoresponder','ar'],custom:['customcommand','cc','cc-delete','cc-list'],afk:['afk'],stars:['stars','starleaderboard','starconfig','starboard'],voice:['tempvoice','voice'],configuration:['permissions','perm','emoji','emoji-list','config','prefix','enable','disable']};
 const names={home:'🏠 Home',moderation:'🛡️ Moderation',security:'🔐 Security',logging:'📋 Logging',leveling:'📈 Leveling',economy:'💰 Economy',music:'🎧 Music',tickets:'🎫 Tickets & Applications',giveaways:'🎉 Giveaways',fun:'🎭 Fun',counters:'📊 Counters',memberstats:'📈 Member & User Stats',notifications:'🔔 Notifications',invites:'🔗 Invites',announcements:'📢 Announcements',roles:'🎭 Roles',channels:'📁 Channels',welcome:'👋 Welcome',autoresponder:'🤖 Auto Responder',custom:'⚙️ Custom Commands',afk:'💤 AFK',stars:'⭐ Stars',voice:'🔊 Voice',configuration:'✨ Configuration'};
 const em=['✦','◆','◇','✧','●','◈'];
 const colors=[0x5865F2,0x7C3AED,0x06B6D4,0x3B82F6,0x8B5CF6,0x4F46E5];
 const color=()=>colors[Math.floor(Date.now()/8000)%colors.length];
 const footer={text:'LIGHTCORE  •  HELP CENTER'};
 function help(cat='home'){
  if(!groups[cat])cat='home';
  const options=Object.keys(groups).map(k=>({label:names[k].replace(/^\S+\s/,''),value:k,emoji:names[k].split(' ')[0]}));
  const total=Object.values(groups).reduce((n,x)=>n+x.length,0);
  if(cat==='home')return {embeds:[new EmbedBuilder().setAuthor({name:'LIGHTCORE  •  COMMAND CENTER',iconURL:client.user?.displayAvatarURL?.({size:64})}).setTitle('✦ Help Center').setDescription(`**Your all-in-one Discord control center.**\n\n> **Prefix**  \`${P}\`\n> **Categories**  \`${Object.keys(groups).length}\`\n> **Commands indexed**  \`${total}\`\n\n${Object.keys(groups).map((k,i)=>`${em[i%em.length]} **${names[k]}**  ·  \`${groups[k].length}\` commands\n   └ ${P}help ${k}`).join('\n')}\n\n**QUICK GUIDE**\nSelect a category below to explore its commands.\n<:sparkles:> Every command keeps its own permissions and feature behavior.`).setColor(color()).setFooter(footer).setTimestamp()],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('lc_help_ordered').setPlaceholder('✦  Browse command categories').addOptions(options.slice(0,25)))]};
  const list=groups[cat].map((x,i)=>`${em[i%em.length]}  \`${P}${x}\``).join('\n');
  const note=cat==='tickets'?`\n\n**PERMISSIONS & FLOW**\n> 🛡️ Setup/edit/panels/categories → **Manage Server**\n> 🎫 Ticket actions → **Staff role / Manage Channels**\n> 📜 Each ticket category supports its own logs/transcripts.`:cat==='economy'?`\n\n**ECONOMY**\n> 👤 Balance, daily, work, pay, richlist & luck → members\n> 🔐 Economy management → configured economy owner`:'';
  return {embeds:[new EmbedBuilder().setAuthor({name:`LIGHTCORE  •  ${names[cat].replace(/^\S+\s/,'').toUpperCase()}`,iconURL:client.user?.displayAvatarURL?.({size:64})}).setTitle(`${names[cat]}  ›  Commands`).setDescription(`**${groups[cat].length} commands available**\n\n${list}${note}\n\n> ✦ Use \`${P}help\` to return to the main menu.`).setColor(color()).setFooter({text:'LIGHTCORE  •  COMMAND INDEX'}).setTimestamp()],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('lc_help_ordered_home').setLabel('Help Home').setEmoji('🏠').setStyle(ButtonStyle.Secondary))]};
 }
 const marker=Symbol.for('lightcore.helpFinalInstalled');if(client[marker])return;client[marker]=true;const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c==='help'||c==='h'){await m.reply(help((a[0]||'home').toLowerCase()));return}return old(m)}catch(e){console.error('[HELP ORDERED]',e)}})}client.on('interactionCreate',async i=>{try{if(i.isStringSelectMenu()&&i.customId==='lc_help_ordered')return i.update(help(i.values[0]));if(i.isButton()&&i.customId==='lc_help_ordered_home')return i.update(help('home'))}catch(e){console.error('[HELP INTERACTION]',e)}});
};
