const fs=require('fs'),path=require('path');
const {EmbedBuilder,PermissionFlagsBits}=require('discord.js');
module.exports=function attachInviteTracker(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','invites.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));const data=g=>db[g]??(db[g]={invites:{},members:{}});const cache=new Map();
 const snapshot=async guild=>{try{const col=await guild.invites.fetch();return Object.fromEntries(col.map(i=>[i.code,{uses:i.uses||0,inviter:i.inviter?.id||null,channel:i.channelId||null}]))}catch{return {}}};
 client.once('ready',async()=>{for(const g of client.guilds.cache.values())cache.set(g.id,await snapshot(g));console.log('[INVITES] Invite cache initialized');});
 client.on('inviteCreate',async inv=>{const old=cache.get(inv.guild.id)||{};old[inv.code]={uses:inv.uses||0,inviter:inv.inviter?.id||null,channel:inv.channelId||null};cache.set(inv.guild.id,old)});
 client.on('inviteDelete',async inv=>{const old=cache.get(inv.guild.id)||{};delete old[inv.code];cache.set(inv.guild.id,old)});
 client.on('guildMemberAdd',async mem=>{const g=data(mem.guild.id),before=cache.get(mem.guild.id)||{},after=await snapshot(mem.guild),used=Object.entries(after).find(([code,x])=>(x.uses||0)>(before[code]?.uses||0));cache.set(mem.guild.id,after);if(!used)return;const inviter=used[1].inviter;if(!inviter)return;const r=g.invites[inviter]??(g.invites[inviter]={joins:0,leaves:0,bonus:0});r.joins++;g.members[mem.id]={inviter,code:used[0],joined:Date.now()};save();});
 client.on('guildMemberRemove',mem=>{const g=data(mem.guild.id),x=g.members[mem.id];if(!x)return;const r=g.invites[x.inviter];if(r){r.joins=Math.max(0,r.joins-1);r.leaves=(r.leaves||0)+1;}save()});
 client.on('messageCreate',async m=>{if(m.author.bot||!m.guild||!m.content.startsWith(P))return;const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(!['invites','invite','invites-leaderboard','invite-leaderboard','invites-reset'].includes(c))return;const g=data(m.guild.id);if(c==='invites-reset'){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply('❌ Manage Server required.');g.invites={};g.members={};save();return m.reply('✅ Invite statistics reset.');}const target=m.mentions.users.first()||m.author;if(c.includes('leaderboard')){const top=Object.entries(g.invites).sort((a,b)=>(b[1].joins||0)-(a[1].joins||0)).slice(0,10);return m.reply({embeds:[new EmbedBuilder().setTitle('🔗 Invite Leaderboard').setDescription(top.length?top.map(([id,x],i)=>`**${i+1}.** <@${id}> — **${x.joins||0}** joins | **${x.leaves||0}** leaves`).join('\n'):'No invite data yet.').setColor(0x5865f2)]});}const id=target.id,x=g.invites[id]||{joins:0,leaves:0,bonus:0};return m.reply({embeds:[new EmbedBuilder().setTitle(`🔗 Invites • ${target.username}`).setDescription(`**Joins:** ${x.joins||0}\n**Leaves:** ${x.leaves||0}\n**Bonus:** ${x.bonus||0}\n**Net:** ${(x.joins||0)-(x.leaves||0)}`).setColor(0x5865f2)]});});
 console.log('[INVITES] Invite tracking loaded');
};