const fs=require('fs');const path=require('path');const {ChannelType,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
module.exports=function attachMembersStats(client,prefix='.'){
 const P=prefix||'.';const file=path.join(process.cwd(),'data','members-stats.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
 const fresh=()=>({enabled:false,category:null,channels:{total:null,humans:null,bots:null,online:null,idle:null,dnd:null,offline:null,voice:null,boosts:null}});const gd=id=>{const d=db[id]||(db[id]=fresh()),f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];return d};
 const stats=g=>{const members=g.memberCount||g.members.cache.size;const ms=[...g.members.cache.values()];const bots=ms.filter(m=>m.user.bot).length;const humans=Math.max(0,members-bots);const online=ms.filter(m=>m.presence?.status==='online').length;const idle=ms.filter(m=>m.presence?.status==='idle').length;const dnd=ms.filter(m=>m.presence?.status==='dnd').length;const offline=Math.max(0,members-online-idle-dnd);const voice=g.channels.cache.filter(c=>[ChannelType.GuildVoice,ChannelType.GuildStageVoice].includes(c.type)).reduce((n,c)=>n+c.members.size,0);return {total:members,humans,bots,online,idle,dnd,offline,voice,boosts:g.premiumSubscriptionCount||0}};
 const templates={total:'👥・Members: {count}',humans:'👤・Humans: {count}',bots:'🤖・Bots: {count}',online:'🟢・Online: {count}',idle:'🌙・Idle: {count}',dnd:'⛔・DND: {count}',offline:'⚫・Offline: {count}',voice:'🔊・In Voice: {count}',boosts:'🚀・Boosts: {count}'};
 async function refresh(g){const d=gd(g.id);if(!d.enabled)return;const s=stats(g);for(const [type,id] of Object.entries(d.channels)){const ch=g.channels.cache.get(id);if(!ch)continue;const name=templates[type].replace('{count}',String(s[type]??0)).slice(0,100);if(ch.name!==name)await ch.setName(name).catch(()=>{})}}
 async function setup(m){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply(`❌ You need **Manage Server** to use ${P}membersstats setup.`);const d=gd(m.guild.id);d.enabled=true;let cat=d.category?m.guild.channels.cache.get(d.category):null;if(!cat)cat=m.guild.channels.cache.find(c=>c.type===ChannelType.GuildCategory&&c.name==='📊・MEMBER STATS');if(!cat)cat=await m.guild.channels.create({name:'📊・MEMBER STATS',type:ChannelType.GuildCategory,permissionOverwrites:[{id:m.guild.roles.everyone.id,deny:[PermissionFlagsBits.Connect]}]});d.category=cat.id;for(const type of Object.keys(templates)){let ch=d.channels[type]?m.guild.channels.cache.get(d.channels[type]):null;if(!ch)ch=m.guild.channels.cache.find(c=>c.parentId===cat.id&&c.type===ChannelType.GuildVoice&&c.name.startsWith(templates[type].split('{count}')[0]));if(!ch)ch=await m.guild.channels.create({name:templates[type].replace('{count}',String(stats(m.guild)[type])),type:ChannelType.GuildVoice,parent:cat.id,permissionOverwrites:[{id:m.guild.roles.everyone.id,deny:[PermissionFlagsBits.Connect]}]});d.channels[type]=ch.id}save();await refresh(m.guild);return m.reply(`✅ **Member Stats enabled**\nCreated/managed **${Object.keys(templates).length}** live counters.`)}
 function panel(g){const s=stats(g);return {embeds:[new EmbedBuilder().setTitle('📊 Member Statistics').setDescription(`**Total Members:** ${s.total}\n**Humans:** ${s.humans}\n**Bots:** ${s.bots}\n\n🟢 **Online:** ${s.online}\n🌙 **Idle:** ${s.idle}\n⛔ **DND:** ${s.dnd}\n⚫ **Offline:** ${s.offline}\n\n🔊 **In Voice:** ${s.voice}\n🚀 **Boosts:** ${s.boosts}`).setFooter({text:'Live server statistics'}).setTimestamp()],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('lc_members_refresh').setLabel('Refresh').setEmoji('🔄').setStyle(ButtonStyle.Secondary))]}}
 async function command(m,a){const sub=(a.shift()||'view').toLowerCase();if(sub==='setup'||sub==='enable')return setup(m);if(sub==='off'||sub==='disable'){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild)&&m.guild.ownerId!==m.author.id)return m.reply('❌ You need Manage Server.');gd(m.guild.id).enabled=false;save();return m.reply('✅ Member Stats disabled. Existing channels were left untouched.')}if(sub==='refresh'){await refresh(m.guild);return m.reply('🔄 Member counters refreshed.')}if(sub==='status'||sub==='config')return m.reply({embeds:[new EmbedBuilder().setTitle('📊 Member Stats Status').setDescription(`**Status:** ${gd(m.guild.id).enabled?'🟢 Enabled':'🔴 Disabled'}\n**Counters:** ${Object.keys(templates).length}\n**Data:** live Discord guild/member data`) ]});return m.reply(panel(m.guild))}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c==='membersstats'||c==='memberstats'||c==='member-stats'||c==='mstats')return command(m,a);return old(m)}catch(e){console.error('[MEMBERS STATS]',e)}})}
 const updateAll=()=>Promise.all([...client.guilds.cache.values()].map(refresh));client.on('guildMemberAdd',m=>refresh(m.guild).catch(()=>{}));client.on('guildMemberRemove',m=>refresh(m.guild).catch(()=>{}));client.on('presenceUpdate',(_,m)=>refresh(m.guild).catch(()=>{}));client.on('voiceStateUpdate',s=>refresh(s.guild).catch(()=>{}));client.on('guildUpdate',g=>refresh(g).catch(()=>{}));client.on('ready',()=>{updateAll().catch(()=>{});setInterval(()=>updateAll().catch(()=>{}),30000).unref()});client.on('interactionCreate',async i=>{if(i.isButton()&&i.customId==='lc_members_refresh'){try{await i.update(panel(i.guild))}catch{}}});
};
