const {EmbedBuilder}=require('discord.js');
module.exports=function attachMembersStats(client,prefix='.'){
 const P=prefix||'.';
 const fmt=n=>Number(n||0).toLocaleString();
 const memberStats=(g,userId)=>{const m=userId?g.members.cache.get(userId):null;const members=g.members.cache;const online=[...members.values()].filter(x=>x.presence?.status&&x.presence.status!=='offline').length;const voice=[...members.values()].filter(x=>x.voice?.channelId).length;return {total:g.memberCount||members.size,humans:[...members.values()].filter(x=>!x.user.bot).length,bots:[...members.values()].filter(x=>x.user.bot).length,online,idle:[...members.values()].filter(x=>x.presence?.status==='idle').length,dnd:[...members.values()].filter(x=>x.presence?.status==='dnd').length,voice,boosts:g.premiumSubscriptionCount||0,user:m};};
 const serverEmbed=g=>new EmbedBuilder().setTitle(`📊 ${g.name} • Server Stats`).setDescription(`**Members**\n👥 Total: **${fmt(memberStats(g).total)}**`).setThumbnail(g.iconURL({size:256})).setFooter({text:'LightCore • Live server statistics'}).setTimestamp();
 const userEmbed=(g,u)=>{const s=memberStats(g,u.id);const m=s.user;const joined=m?.joinedAt?Math.floor(m.joinedAt.getTime()/1000):null;return new EmbedBuilder().setTitle(`📊 ${u.username} • Stats`).setThumbnail(u.displayAvatarURL({size:256})).setDescription(`**User**\n👤 ${u}\n🆔 \`${u.id}\`\n\n**Server**\n🏠 ${g.name}\n📅 Joined: ${joined?`<t:${joined}:R>`:'Unknown'}\n${m?.premiumSince?'🚀 Server Booster: **Yes**':'🚀 Server Booster: **No**'}\n\n**Server snapshot**\n👥 Members: **${fmt(s.total)}**\n🟢 Online: **${fmt(s.online)}**`).setFooter({text:'LightCore • Member profile stats'}).setTimestamp();};
 const messageEmbed=g=>new EmbedBuilder().setTitle(`💬 ${g.name} • Message Stats`).setDescription(`Message-level analytics are available through the server message statistics system. Use \`${P}messages\` for the server view and \`${P}messages @user\` for a member view.`).setTimestamp();
 async function command(m,a){const target=m.mentions.users.first();const sub=(a[0]||'').toLowerCase();if(sub==='help')return m.reply({embeds:[new EmbedBuilder().setTitle('📊 Member Stats').setDescription(`**${P}stats** — your profile/server stats\n**${P}stats @user** — another member's stats\n**${P}serverstats** — server statistics\n**${P}members** — member statistics\n**${P}messages** — message statistics`)]});if(['server','serverstats','members','membersstats'].includes(sub))return m.reply({embeds:[serverEmbed(m.guild)]});if(sub==='messages')return m.reply({embeds:[messageEmbed(m.guild)]});return m.reply({embeds:[userEmbed(m.guild,target||m.author)]});}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/);const c=(a.shift()||'').toLowerCase();if(['stats','stat','member','memberstats','membersstats','serverstats','members'].includes(c))return command(m,a);if(c==='messages')return command(m,['messages',...a]);return old(m)}catch(e){console.error('[STATS]',e)}})}
};