const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
module.exports=function attachMembersStats(client,prefix='.'){
 const P=prefix||'.';
 const fmt=n=>Number(n||0).toLocaleString();
 const memberStats=(g,userId)=>{const m=userId?g.members.cache.get(userId):null;const msgs=g.members.cache;const online=[...msgs.values()].filter(x=>x.presence?.status&&x.presence.status!=='offline').length;const voice=[...msgs.values()].filter(x=>x.voice?.channelId).length;return {total:g.memberCount||msgs.size,humans:[...msgs.values()].filter(x=>!x.user.bot).length,bots:[...msgs.values()].filter(x=>x.user.bot).length,online,idle:[...msgs.values()].filter(x=>x.presence?.status==='idle').length,dnd:[...msgs.values()].filter(x=>x.presence?.status==='dnd').length,voice,boosts:g.premiumSubscriptionCount||0,user:m};};
 const serverEmbed=g=>{const s=memberStats(g);return new EmbedBuilder().setTitle(`📊 ${g.name} • Server Stats`).setDescription(`**Members**\n👥 Total: **${fmt(s.total)}**\n👤 Humans: **${fmt(s.humans)}**\n🤖 Bots: **${fmt(s.bots)}**\n\n**Presence**\n🟢 Online: **${fmt(s.online)}**\n🌙 Idle: **${fmt(s.idle)}**\n⛔ DND: **${fmt(s.dnd)}**\n⚫ Offline: **${fmt(Math.max(0,s.total-s.online))}**\n\n🔊 In Voice: **${fmt(s.voice)}**\n🚀 Boosts: **${fmt(s.boosts)}**`).setThumbnail(g.iconURL({size:256})).setFooter({text:'LightCore • Live server statistics'}).setTimestamp()};
 const userEmbed=(g,u)=>{const s=memberStats(g,u.id);const m=s.user;const joined=m?.joinedAt?Math.floor(m.joinedAt.getTime()/1000):null;return new EmbedBuilder().setTitle(`📊 ${u.username} • Stats`).setThumbnail(u.displayAvatarURL({size:256})).setDescription(`**User**\n👤 ${u}\n🆔 \`${u.id}\`\n\n**Server**\n🏠 ${g.name}\n📅 Joined: ${joined?`<t:${joined}:R>`:'Unknown'}\n${m?.premiumSince?'🚀 Server Booster: **Yes**':'🚀 Server Booster: **No**'}\n\n**Server snapshot**\n👥 Members: **${fmt(s.total)}**\n🟢 Online: **${fmt(s.online)}**`)}).setFooter({text:'LightCore • Member profile stats'}).setTimestamp()};
 const messageEmbed=(g)=>new EmbedBuilder().setTitle(`💬 ${g.name} • Message Stats`).setDescription('Message-level analytics are available through the server message statistics system. Use `.messages` for the server leaderboard and `.messages @user` for a member view.').setTimestamp();
 async function command(m,a){const target=m.mentions.users.first();const sub=(a[0]||'').toLowerCase();if(sub==='help')return m.reply({embeds:[new EmbedBuilder().setTitle('📊 Member Stats').setDescription(`**${P}stats** — your profile/server stats\n**${P}stats @user** — another member's stats\n**${P}serverstats** — server statistics\n**${P}members** — member statistics\n**${P}members top** — top server members\n**${P}messages** — message statistics\n**${P}messages @user** — member message stats`)]});if(sub==='server'||sub==='serverstats'||sub==='members'||sub==='membersstats')return m.reply({embeds:[serverEmbed(m.guild)]});if(sub==='messages')return m.reply({embeds:[messageEmbed(m.guild)]});return m.reply({embeds:[userEmbed(m.guild,target||m.author)]});}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/);const c=(a.shift()||'').toLowerCase();if(['stats','stat','s!u','member','memberstats','membersstats','serverstats','members'].includes(c))return command(m,a);if(c==='messages')return command(m,['messages',...a]);return old(m)}catch(e){console.error('[STATS]',e)}})}
};
