const fs=require('fs');const path=require('path');const https=require('https');const {EmbedBuilder}=require('discord.js');
module.exports=function attach(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','notifier.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));const guild=id=>db[id]||(db[id]={feeds:[]});
 const get=url=>new Promise((resolve,reject)=>{if(!/^https:\/\//i.test(url))return reject(new Error('Only HTTPS feed URLs are supported.'));const req=https.get(url,{headers:{'User-Agent':'LightCore-Notifier/1.0'}},res=>{let s='';res.setEncoding('utf8');res.on('data',x=>{s+=x;if(s.length>500000)req.destroy();});res.on('end',()=>resolve(s));});req.setTimeout(10000,()=>req.destroy(new Error('timeout')));req.on('error',reject);});
 const parse=x=>{const block=x.match(/<(?:item|entry)[^>]*>[\s\S]*?<\/(?:item|entry)>/i)?.[0];if(!block)return null;const title=(block.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'New update').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,'').trim();const link=block.match(/<link[^>]*href=["']([^"']+)["']/i)?.[1]||block.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1]?.trim();const id=(block.match(/<(?:guid|id)[^>]*>([\s\S]*?)<\/(?:guid|id)>/i)?.[1]||link||title).replace(/<[^>]+>/g,'').trim();return{title,link,id};};
 async function poll(){for(const gid of Object.keys(db)){for(const f of db[gid].feeds||[]){try{const item=parse(await get(f.url));if(!item||item.id===f.last)continue;if(!f.last){f.last=item.id;save();continue;}f.last=item.id;save();const ch=client.channels.cache.get(f.channel);if(ch?.isTextBased())await ch.send({embeds:[new EmbedBuilder().setTitle(`🔔 ${f.name}`).setDescription(`**${item.title}**${item.link?`\n\n[View update](${item.link})`:''}`).setColor(0x5865f2).setTimestamp()]});}catch(e){console.error('[NOTIFIER]',f.name,e.message);}}}}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c!=='notify')return old(m);if(!m.member.permissions.has('ManageGuild')&&m.guild.ownerId!==m.author.id)return m.reply('❌ Manage Server required.');const g=guild(m.guild.id),sub=(a.shift()||'').toLowerCase();if(sub==='add'){const ch=m.mentions.channels.first(),url=a.find(x=>/^https:\/\//i.test(x)),name=a.filter(x=>x!==url).join(' ')||'Feed';if(!ch||!url)return m.reply(`Usage: ${P}notify add <name> <HTTPS RSS/Atom URL> #channel`);g.feeds.push({name,url,channel:ch.id,last:''});save();return m.reply(`🔔 Added **${name}**. New feed items will be posted in ${ch}.`);}if(sub==='list')return m.reply({embeds:[new EmbedBuilder().setTitle('🔔 NOTIFIER FEEDS').setDescription(g.feeds.length?g.feeds.map((f,i)=>`**${i+1}. ${f.name}** → <#${f.channel}>`).join('\n'):'No feeds configured.').setColor(0x5865f2)]});if(sub==='remove'){const n=Number(a[0])-1;if(!Number.isInteger(n)||!g.feeds[n])return m.reply(`Usage: ${P}notify remove <number>`);const f=g.feeds.splice(n,1)[0];save();return m.reply(`🗑️ Removed **${f.name}**.`);}if(sub==='test'){await poll();return m.reply('🔔 Notifier check completed.');}return m.reply(`Usage: ${P}notify add|list|remove|test`);}catch(e){console.error('[NOTIFIER CMD]',e);}});}
 setInterval(()=>poll().catch(()=>{}),60000).unref();
};
