const fs=require('fs'),path=require('path');const {AuditLogEvent,EmbedBuilder,PermissionFlagsBits}=require('discord.js');
module.exports=function attach(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','raid-shield.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
 const fresh=()=>({enabled:false,log:null,trusted:[],limits:{channelDelete:3,roleDelete:3,ban:3,kick:5,webhook:5},hits:{}});const gd=id=>{const d=db[id]||(db[id]=fresh()),f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];return d};const admin=m=>m.guild.ownerId===m.author.id||m.member.permissions.has(PermissionFlagsBits.ManageGuild);const trusted=(g,id)=>g.ownerId===id||gd(g.id).trusted.includes(id);
 const alert=async(g,text)=>{const c=g.channels.cache.get(gd(g.id).log);if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setColor(0xed4245).setTitle('🛡️ LightCore • Raid Shield').setDescription(text).setTimestamp()]}).catch(()=>{})};
 async function inspect(g,type,auditType){const d=gd(g.id);if(!d.enabled)return;const logs=await g.fetchAuditLogs({type:auditType,limit:1}).catch(()=>null),e=logs?.entries.first();if(!e||Date.now()-e.createdTimestamp>10000||!e.executor||trusted(g,e.executor.id))return;const now=Date.now(),old=d.hits[e.executor.id]||{},arr=(old[type]||[]).filter(x=>now-x<10000);arr.push(now);d.hits[e.executor.id]={...old,[type]:arr};save();if(arr.length>=Number(d.limits[type]||3))await alert(g,`**Rapid destructive activity detected**\nExecutor: <@${e.executor.id}>\nEvent: **${type}**\nCount: **${arr.length}/10s**\n\nReview the Discord Audit Log and use your normal moderation controls if action is needed.`)}
 client.on('channelDelete',c=>inspect(c.guild,'channelDelete',AuditLogEvent.ChannelDelete));client.on('roleDelete',r=>inspect(r.guild,'roleDelete',AuditLogEvent.RoleDelete));client.on('guildBanAdd',b=>inspect(b.guild,'ban',AuditLogEvent.MemberBanAdd));client.on('guildMemberRemove',m=>inspect(m.guild,'kick',AuditLogEvent.MemberKick));client.on('webhookUpdate',c=>inspect(c.guild,'webhook',AuditLogEvent.WebhookCreate));
 async function cmd(m,a){if(!admin(m))return m.reply('🚫 **Manage Server** permission required.');const d=gd(m.guild.id),s=(a.shift()||'status').toLowerCase();if(['on','enable'].includes(s)){d.enabled=true;save();return m.reply('🛡️ **Raid Shield enabled.** Rapid destructive activity will be detected and logged.')}if(['off','disable'].includes(s)){d.enabled=false;save();return m.reply('🔴 Raid Shield disabled.')}if(s==='log'){const c=m.mentions.channels.first();if(!c)return m.reply(`Usage: ${P}raidshield log #channel`);d.log=c.id;save();return m.reply(`✅ Security alerts → ${c}`)}if(s==='trust'){const u=m.mentions.users.first();if(!u)return m.reply(`Usage: ${P}raidshield trust @user`);if(!d.trusted.includes(u.id))d.trusted.push(u.id);save();return m.reply(`✅ Trusted ${u}.`)}if(s==='untrust'){const u=m.mentions.users.first();if(!u)return m.reply(`Usage: ${P}raidshield untrust @user`);d.trusted=d.trusted.filter(x=>x!==u.id);save();return m.reply(`✅ Removed ${u} from trusted users.`)}if(s==='limit'){const k=a[0],n=Math.max(1,Math.min(50,Number(a[1])||0));if(!Object.hasOwn(d.limits,k)||!n)return m.reply(`Types: ${Object.keys(d.limits).join(', ')}`);d.limits[k]=n;save();return m.reply(`✅ **${k}** threshold set to **${n}/10s**.`)}return m.reply({embeds:[new EmbedBuilder().setTitle('🛡️ LIGHTCORE • RAID SHIELD').setColor(0xed4245).setDescription(`**Status:** ${d.enabled?'🟢 Enabled':'🔴 Disabled'}\n**Alert channel:** ${d.log?`<#${d.log}>`:'Not configured'}\n\nDetects rapid channel/role deletion, bans, kicks and webhook changes and sends an audit alert.\n\n\`${P}raidshield on/off\`\n\`${P}raidshield log #channel\`\n\`${P}raidshield trust @user\`\n\`${P}raidshield untrust @user\`\n\`${P}raidshield limit <type> <number>\``)]})}
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c==='raidshield')return cmd(m,a);return old(m)}catch(e){console.error('[RAID-SHIELD]',e)}})}
};
