const fs=require('fs'),path=require('path');const {ChannelType,PermissionFlagsBits}=require('discord.js');
module.exports=function attach(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','template-voice.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
 const fresh=()=>({hub:null,category:null,template:'🔊・{user}’s room',limit:0,rooms:{}});const gd=id=>{const d=db[id]||(db[id]=fresh()),f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];return d};
 const admin=m=>m.member.permissions.has(PermissionFlagsBits.ManageChannels)||m.guild.ownerId===m.author.id;
 async function setup(m,a){if(!admin(m))return m.reply('🚫 **Manage Channels** is required.');const d=gd(m.guild.id),name=a.join(' ')||d.template;d.template=name;let cat=d.category&&m.guild.channels.cache.get(d.category);if(!cat)cat=await m.guild.channels.create({name:'🔊・VOICE ROOMS',type:ChannelType.GuildCategory});d.category=cat.id;let hub=d.hub&&m.guild.channels.cache.get(d.hub);if(!hub)hub=await m.guild.channels.create({name:'➕・Join To Create',type:ChannelType.GuildVoice,parent:cat.id});d.hub=hub.id;save();return m.reply(`✅ **Template Voice enabled**\nHub: ${hub}\nTemplate: \`${d.template}\``)}
 async function config(m,a){if(!admin(m))return m.reply('🚫 **Manage Channels** is required.');const d=gd(m.guild.id),k=(a.shift()||'').toLowerCase(),v=a.join(' ');if(k==='template'&&v){d.template=v;save();return m.reply('✅ Voice template updated.')}if(k==='limit'){const n=Math.max(0,Math.min(99,Number(v)||0));d.limit=n;save();return m.reply(`✅ User limit set to **${n||'unlimited'}**.`)}if(k==='category'){const c=m.mentions.channels.first();if(!c||c.type!==ChannelType.GuildCategory)return m.reply(`Usage: ${P}voice category #category`);d.category=c.id;save();return m.reply('✅ Voice category updated.')}return m.reply(`Usage: ${P}voice template <name>\n${P}voice limit <number>\n${P}voice category #category`)}
 client.on('voiceStateUpdate',async(o,n)=>{try{const d=gd(n.guild.id);if(n.channelId===d.hub){const ch=await n.guild.channels.create({name:d.template.replaceAll('{user}',n.member.displayName).replaceAll('{id}',n.member.id).replaceAll('{server}',n.guild.name).slice(0,100),type:ChannelType.GuildVoice,parent:d.category||d.hub,userLimit:d.limit,permissionOverwrites:[{id:n.guild.roles.everyone.id,allow:[PermissionFlagsBits.Connect,PermissionFlagsBits.ViewChannel]}]});await n.setChannel(ch).catch(()=>{});d.rooms[n.member.id]=ch.id;save()}if(o.channelId&&o.channelId!==d.hub){const ch=o.guild.channels.cache.get(o.channelId);if(ch&&Object.values(d.rooms).includes(ch.id)&&ch.members.size===0){await ch.delete().catch(()=>{});for(const [u,id] of Object.entries(d.rooms))if(id===ch.id)delete d.rooms[u];save()}}}catch(e){console.error('[TEMPLATE VOICE]',e)}});
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c==='voice'&&['template','setup'].includes((a[0]||'').toLowerCase())){a.shift();return setup(m,a)}if(c==='voice'&&['limit','category'].includes((a[0]||'').toLowerCase()))return config(m,a);return old(m)}catch(e){console.error('[TEMPLATE VOICE CMD]',e)}})});
};
