const fs=require('fs'),path=require('path');const {ChannelType,PermissionFlagsBits,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,UserSelectMenuBuilder}=require('discord.js');
module.exports=function attach(client,prefix='.'){
 const P=prefix||'.',file=path.join(process.cwd(),'data','tempvoice.json');fs.mkdirSync(path.dirname(file),{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(file,'utf8')||'{}')}catch{};const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
 const fresh=()=>({hub:null,category:null,interfaceChannel:null,template:'🔊・{user}・room',limit:0,rooms:{}});const gd=id=>{const d=db[id]||(db[id]=fresh()),f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];return d};
 const admin=m=>m.member.permissions.has(PermissionFlagsBits.ManageGuild)||m.guild.ownerId===m.author.id;
 const roomOf=(g,userId)=>{const d=gd(g.id),id=d.rooms[userId];return id?g.channels.cache.get(id):null};
 const ownerOf=(g,ch)=>{const d=gd(g.id);for(const [u,id] of Object.entries(d.rooms))if(id===ch?.id)return u;return null};
 const controls=()=>({embeds:[new EmbedBuilder().setTitle('🎛️ Temporary Voice Interface').setDescription('**Join ➕・Join to Create** to receive your own temporary voice room.\n\n**Room controls**\n🔒 Lock / 🔓 Unlock\n👻 Hide / 👁️ Show\n✏️ Rename / 🔢 Limit\n👢 Kick / 👑 Transfer\n🎤 Claim / ℹ️ Info\n\nOnly the current room owner can manage the room. The room is removed automatically when empty.').setColor(0x5865f2).setFooter({text:'LightCore • Temp Voice'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tv_lock').setLabel('Lock').setEmoji('🔒').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('tv_unlock').setLabel('Unlock').setEmoji('🔓').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('tv_hide').setLabel('Hide').setEmoji('👻').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('tv_show').setLabel('Show').setEmoji('👁️').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tv_rename').setLabel('Rename').setEmoji('✏️').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('tv_limit').setLabel('Limit').setEmoji('🔢').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('tv_kick').setLabel('Kick').setEmoji('👢').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('tv_transfer').setLabel('Transfer').setEmoji('👑').setStyle(ButtonStyle.Success)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tv_permit').setLabel('Permit').setEmoji('✅').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('tv_reject').setLabel('Reject').setEmoji('🚫').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('tv_claim').setLabel('Claim').setEmoji('🎤').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('tv_info').setLabel('Info').setEmoji('ℹ️').setStyle(ButtonStyle.Secondary))]});
 async function setup(m){if(!admin(m))return m.reply('🚫 **Manage Server** is required.');const d=gd(m.guild.id);let cat=d.category&&m.guild.channels.cache.get(d.category);if(!cat)cat=await m.guild.channels.create({name:'🔊・TEMP VOICE',type:ChannelType.GuildCategory});d.category=cat.id;let hub=d.hub&&m.guild.channels.cache.get(d.hub);if(!hub)hub=await m.guild.channels.create({name:'➕・Join to Create',type:ChannelType.GuildVoice,parent:cat.id});d.hub=hub.id;let ic=d.interfaceChannel&&m.guild.channels.cache.get(d.interfaceChannel);if(!ic)ic=await m.guild.channels.create({name:'🎛️・voice-interface',type:ChannelType.GuildText,parent:cat.id});d.interfaceChannel=ic.id;await ic.send(controls()).catch(()=>{});save();return m.reply(`✅ **Temp Voice is ready.**\n➕ Join channel: ${hub}\n🎛️ Interface: ${ic}\n📁 Category: ${cat}`)}
 async function config(m,a){if(!admin(m))return m.reply('🚫 **Manage Server** is required.');const d=gd(m.guild.id),k=(a.shift()||'').toLowerCase(),v=a.join(' ');if(k==='template'&&v){d.template=v;save();return m.reply('✅ Temp voice name template updated.')}if(k==='limit'){d.limit=Math.max(0,Math.min(99,Number(v)||0));save();return m.reply(`✅ Default limit: **${d.limit||'unlimited'}**.`)}if(k==='interface'){const c=m.mentions.channels.first();if(!c||c.type!==ChannelType.GuildText)return m.reply(`Usage: ${P}tempvoice interface #channel`);d.interfaceChannel=c.id;save();await c.send(controls()).catch(()=>{});return m.reply('✅ Interface channel updated and panel sent.')}return m.reply(`Usage: ${P}tempvoice template <name>\n${P}tempvoice limit <number>\n${P}tempvoice interface #channel`)}
 async function create(n){const g=n.guild,d=gd(g.id);if(n.channelId!==d.hub||!n.member)return;if(roomOf(g,n.member.id))return;const name=d.template.replaceAll('{user}',n.member.displayName).replaceAll('{username}',n.member.user.username).replaceAll('{id}',n.member.id).replaceAll('{server}',g.name).slice(0,100);const ch=await g.channels.create({name,type:ChannelType.GuildVoice,parent:d.category||undefined,userLimit:d.limit,permissionOverwrites:[{id:g.roles.everyone.id,allow:[PermissionFlagsBits.Connect,PermissionFlagsBits.ViewChannel]},{id:n.member.id,allow:[PermissionFlagsBits.Connect,PermissionFlagsBits.ViewChannel,PermissionFlagsBits.MoveMembers,PermissionFlagsBits.ManageChannels]}]});d.rooms[n.member.id]=ch.id;save();await n.setChannel(ch).catch(()=>{});}
 async function cleanup(n){const g=n.guild,d=gd(g.id);for(const [u,id] of Object.entries(d.rooms)){const ch=g.channels.cache.get(id);if(!ch||ch.members.size===0){if(ch)await ch.delete().catch(()=>{});delete d.rooms[u]}}save()}
 client.on('voiceStateUpdate',async(o,n)=>{try{await create(n);await cleanup(n)}catch(e){console.error('[TEMP VOICE]',e)}});
 const old=client.listeners('messageCreate').at(-1);if(old){client.removeListener('messageCreate',old);client.on('messageCreate',async m=>{try{if(m.author.bot||!m.guild)return;if(!m.content.startsWith(P))return old(m);const a=m.content.slice(P.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();if(c==='tempvoice'||c==='tempvc'){const s=(a.shift()||'setup').toLowerCase();if(s==='setup')return setup(m);if(['template','limit','interface'].includes(s))return config(m,[s,...a]);if(s==='panel')return m.channel.send(controls());}return old(m)}catch(e){console.error('[TEMP VOICE CMD]',e)}})}
 const ownerCheck=(i,ch)=>ownerOf(i.guild,ch)===i.user.id;
 const select=(id,placeholder)=>new UserSelectMenuBuilder().setCustomId(id).setPlaceholder(placeholder).setMinValues(1).setMaxValues(1);
 client.on('interactionCreate',async i=>{try{
  if(i.isButton()&&i.customId.startsWith('tv_')){
   const ch=roomOf(i.guild,i.user.id);
   if(i.customId==='tv_info'){if(!ch)return i.reply({content:'❌ Join your temporary voice channel first.',ephemeral:true});return i.reply({embeds:[new EmbedBuilder().setTitle('🔊 Your Voice Room').setDescription(`**Channel:** ${ch}\n**Members:** ${ch.members.size}\n**Owner:** <@${ownerOf(i.guild,ch)}>\n**Limit:** ${ch.userLimit||'Unlimited'}\n**Bitrate:** ${Math.round(ch.bitrate/1000)}kbps`).setColor(0x5865f2)],ephemeral:true})}
   if(i.customId==='tv_claim'){const d=gd(i.guild.id);const target=[...i.guild.channels.cache.values()].find(x=>x.type===ChannelType.GuildVoice&&x.members.has(i.user.id)&&Object.values(d.rooms).includes(x.id));if(!target)return i.reply({content:'❌ Join a temporary room first.',ephemeral:true});const previous=ownerOf(i.guild,target);if(previous===i.user.id)return i.reply({content:'✅ You already own this room.',ephemeral:true});if(previous&&target.members.has(previous))return i.reply({content:'❌ The current owner is still in the room.',ephemeral:true});if(previous)delete d.rooms[previous];d.rooms[i.user.id]=target.id;await target.permissionOverwrites.edit(i.user.id,{Connect:true,ViewChannel:true,MoveMembers:true,ManageChannels:true}).catch(()=>{});save();return i.reply({content:'👑 You now own this temporary room.',ephemeral:true})}
   if(!ch)return i.reply({content:'❌ Join your temporary voice channel first.',ephemeral:true});if(!ownerCheck(i,ch))return i.reply({content:'🚫 Only the channel owner can use these controls.',ephemeral:true});
   if(['tv_lock','tv_unlock','tv_hide','tv_show'].includes(i.customId)){const everyone=i.guild.roles.everyone;if(i.customId==='tv_lock')await ch.permissionOverwrites.edit(everyone,{Connect:false});if(i.customId==='tv_unlock')await ch.permissionOverwrites.edit(everyone,{Connect:true,ViewChannel:true});if(i.customId==='tv_hide')await ch.permissionOverwrites.edit(everyone,{ViewChannel:false});if(i.customId==='tv_show')await ch.permissionOverwrites.edit(everyone,{ViewChannel:true});return i.reply({content:`✅ **${i.customId.replace('tv_','').toUpperCase()}** applied.`,ephemeral:true})}
   if(i.customId==='tv_rename'||i.customId==='tv_limit'){const modal=new ModalBuilder().setCustomId(i.customId==='tv_rename'?'tv_modal_name':'tv_modal_limit').setTitle(i.customId==='tv_rename'?'Rename Voice Room':'Set Voice Limit');const input=new TextInputBuilder().setCustomId('value').setLabel(i.customId==='tv_rename'?'New channel name':'Limit (0-99)').setStyle(TextInputStyle.Short).setRequired(true).setValue(i.customId==='tv_rename'?ch.name:String(ch.userLimit||0));modal.addComponents(new ActionRowBuilder().addComponents(input));return i.showModal(modal)}
   if(['tv_kick','tv_transfer','tv_permit','tv_reject'].includes(i.customId)){const map={tv_kick:['tv_kick_user','Select a member to disconnect'],tv_transfer:['tv_transfer_user','Select the new owner'],tv_permit:['tv_permit_user','Select a member to permit'],tv_reject:['tv_reject_user','Select a member to reject']};const [id,ph]=map[i.customId];return i.reply({content:'Select a member:',components:[new ActionRowBuilder().addComponents(select(id,ph))],ephemeral:true})}
  }
  if(i.isModalSubmit()&&['tv_modal_name','tv_modal_limit'].includes(i.customId)){const ch=roomOf(i.guild,i.user.id);if(!ch||!ownerCheck(i,ch))return i.reply({content:'🚫 You do not own a temp room.',ephemeral:true});if(i.customId==='tv_modal_name'){const name=i.fields.getTextInputValue('value').slice(0,100);await ch.setName(name);return i.reply({content:'✏️ Room renamed.',ephemeral:true})}const n=Math.max(0,Math.min(99,Number(i.fields.getTextInputValue('value'))||0));await ch.setUserLimit(n);return i.reply({content:`🔢 Limit set to **${n||'unlimited'}**.`,ephemeral:true})}
  if(i.isUserSelectMenu()&&['tv_kick_user','tv_transfer_user','tv_permit_user','tv_reject_user'].includes(i.customId)){const ch=roomOf(i.guild,i.user.id);if(!ch||!ownerCheck(i,ch))return i.reply({content:'🚫 You do not own a temp room.',ephemeral:true});const target=i.guild.members.cache.get(i.values[0]);if(!target)return i.reply({content:'❌ Member not found.',ephemeral:true});if(i.customId==='tv_kick_user'){if(target.voice.channelId===ch.id)await target.voice.disconnect().catch(()=>{});return i.reply({content:`👢 Disconnected ${target}.`,ephemeral:true})}if(i.customId==='tv_transfer_user'){const d=gd(i.guild.id);delete d.rooms[i.user.id];d.rooms[target.id]=ch.id;await ch.permissionOverwrites.edit(target.id,{Connect:true,ViewChannel:true,MoveMembers:true,ManageChannels:true}).catch(()=>{});await ch.permissionOverwrites.edit(i.user.id,{Connect:true,ViewChannel:true}).catch(()=>{});save();return i.reply({content:`👑 Ownership transferred to ${target}.`,ephemeral:true})}if(i.customId==='tv_permit_user'){await ch.permissionOverwrites.edit(target.id,{Connect:true,ViewChannel:true});return i.reply({content:`✅ ${target} is permitted to join.`,ephemeral:true})}if(i.customId==='tv_reject_user'){await ch.permissionOverwrites.edit(target.id,{Connect:false,ViewChannel:false});if(target.voice.channelId===ch.id)await target.voice.disconnect().catch(()=>{});return i.reply({content:`🚫 ${target} is rejected from this room.`,ephemeral:true})}
  }
 }catch(e){console.error('[TEMP VOICE INTERACTION]',e)}});
};
